// ON THE GO MOVING — Blog Index Posts (auto-generated)
// Generated: 2026-04-07
// ==========================================================================

import { BRAND_IMAGES } from "@/lib/brandImages";

export interface BlogIndexPost {
  slug: string;
  title: string;
  date: string;
  category: string;
  excerpt: string;
  image: string;
  readTime: string;
}

export const BLOG_POSTS: BlogIndexPost[] = [
  {
    slug: "how-to-downsize-your-home",
    title: `5 Tips On How To Downsize Your Home`,
    date: "July 23, 2019",
    category: "Moving Tips",
    excerpt: `We’ve compiled a list of five tips to help you downsize and make the most of your small space. Are you ready? Let’s do this!`,
    image: BRAND_IMAGES.crewEntryway1,
    readTime: "4 min read",
  },
  {
    slug: "hiring-a-good-moving-crew",
    title: `Hiring a Good Moving Crew`,
    date: "August 31, 2016",
    category: "Moving Tips",
    excerpt: `Hiring a reliable moving company can be tough. Here's how you can make sure your moving crew is safe, affordable, and respectful. `,
    image: BRAND_IMAGES.crewCustomerCommercial,
    readTime: "3 min read",
  },
  {
    slug: "moving-tips-how-to-pack-up-your-garage-for-moving",
    title: `Moving Tips: How to Pack Up Your Garage for Moving`,
    date: "December 16, 2016",
    category: "Packing Tips",
    excerpt: `When it comes to moving, packing up the garage can be quite the project. Here are a few helpful moving tips for making the process go swiftly and smoothly.`,
    image: BRAND_IMAGES.truckSeattleSkyline,
    readTime: "5 min read",
  },
  {
    slug: "how-to-help-a-hoarder-move",
    title: `How to Help a Hoarder Move Into a New Home`,
    date: "March 27, 2018",
    category: "Moving Tips",
    excerpt: `By very definition, a hoarder has a lot of belongings, so moving will be a challenge. If you need to help a hoarder move into a new home, but are wondering how `,
    image: BRAND_IMAGES.crewEntryway2,
    readTime: "4 min read",
  },
  {
    slug: "how-to-pack-tv-for-moving",
    title: `How To Pack Your Flat Screen TV for Moving | 4 Expert Tips`,
    date: "November 15, 2019",
    category: "Packing Tips",
    excerpt: `Not sure how to safely pack your TV for moving? Explore four expert tips for quickly and securely transporting your TV to your new home.`,
    image: BRAND_IMAGES.truckBellevueSkyline,
    readTime: "3 min read",
  },
  {
    slug: "5-reasons-to-use-climate-controlled-storage",
    title: `5 Reasons To Use Climate-Controlled Storage`,
    date: "February 7, 2020",
    category: "Storage",
    excerpt: `Moving can be stressful. Some of the stress that comes along with that is making sure all your valubales are kepts safe during the big move. Using climate contr`,
    image: BRAND_IMAGES.storageWarehouse,
    readTime: "4 min read",
  },
  {
    slug: "3-unexpected-challenges-of-moving-across-town",
    title: `3 Unexpected Challenges of Moving Across Town`,
    date: "November 17, 2017",
    category: "Moving Tips",
    excerpt: `If you're moving within the same city or area, prepare for the following unexpected challenges you'll probably face when moving across town.`,
    image: BRAND_IMAGES.crewEntryway3,
    readTime: "3 min read",
  },
  {
    slug: "why-moving-is-the-worst-and-what-to-do-about-it",
    title: `Why Moving Is the Worst and What to do About It`,
    date: "November 21, 2017",
    category: "Moving Tips",
    excerpt: `When it comes to stressful events, isn't the moving process just the worst? Well, we're here to give you some tips on making your move a better experience.`,
    image: BRAND_IMAGES.crewDoorway1,
    readTime: "5 min read",
  },
  {
    slug: "moving-with-kids",
    title: `8 Tips To Help Moving With Kids Go Smoothly`,
    date: "July 23, 2019",
    category: "Moving Tips",
    excerpt: `Moving with kids can feel a bit overwhelming sometimes, but it doesn't have to. To help we've compiled eight tips to help make moving with kids a breeze for you`,
    image: BRAND_IMAGES.crewOverheadEntrance,
    readTime: "5 min read",
  },
  {
    slug: "8-tips-move-bad-weather",
    title: `8 Tips to Help You Move in The Rain`,
    date: "October 8, 2018",
    category: "Moving Costs",
    excerpt: `Moving in bad weather is never easy. These 8 moving tips will help you cope successfully with moving house or apartment in bad weather.`,
    image: BRAND_IMAGES.truckProfessionalLot,
    readTime: "3 min read",
  },
  {
    slug: "why-temporary-storage-is-must-when-moving",
    title: `Why Temporary Storage Is A Must When Moving`,
    date: "December 7, 2017",
    category: "Storage",
    excerpt: `If you're in the middle of moving, you know how stressful the whole process can be. Thankfully, temporary storage can make your entire move much easier.`,
    image: BRAND_IMAGES.storageWarehouse,
    readTime: "3 min read",
  },
  {
    slug: "moving-during-the-holidays-tips-for-reducing-stress",
    title: `Moving During the Holidays: How To Reduce Stress`,
    date: "November 20, 2018",
    category: "Moving Costs",
    excerpt: `The holidays are already a chaotic time of year, but moving can make them even more stressful. Here are some handy tips to help you reduce stress while moving d`,
    image: BRAND_IMAGES.truckKirklandHouse,
    readTime: "4 min read",
  },
  {
    slug: "forgetting-something-5-things-moving",
    title: `Forgetting Something? 5 Things to Do Before Moving`,
    date: "August 15, 2017",
    category: "Moving Tips",
    excerpt: `Moving can be one of the most exciting events of your life, but also one of the most stressful events in your life. The game changer in whether your move is goi`,
    image: BRAND_IMAGES.crewCarryingUpRamp,
    readTime: "4 min read",
  },
  {
    slug: "changing-your-address-essential-checklist",
    title: `An Essential Checklist for Changing Your Address`,
    date: "September 30, 2016",
    category: "Moving Tips",
    excerpt: `Moving means changing your address. Here's a step by step guide on how to change your address and communicate with people who need your new address.`,
    image: BRAND_IMAGES.crewHoodieAtTruck,
    readTime: "4 min read",
  },
  {
    slug: "moving-tips-the-right-way-to-pack-a-bathroom",
    title: `Moving Tips: The Right Way to Pack a Bathroom`,
    date: "October 7, 2016",
    category: "Packing Tips",
    excerpt: `Getting ready for the big move? Here are some helpful moving tips on how to pack your bathroom efficiently and economically.`,
    image: BRAND_IMAGES.truckBrickBuilding,
    readTime: "3 min read",
  },
  {
    slug: "easily-declutter-house",
    title: `How To Easily Declutter Your House`,
    date: "March 28, 2017",
    category: "Moving Tips",
    excerpt: `Whether you need someone to help out with child care so you can sort through your household closets in peace, or you need a professional organizer who knows how`,
    image: BRAND_IMAGES.crewFloorProtection2,
    readTime: "3 min read",
  },
  {
    slug: "7-terrible-mistakes-to-avoid-when-moving",
    title: `7 Moving Mistakes You Never Want To Make`,
    date: "January 28, 2020",
    category: "Moving Tips",
    excerpt: `Moving can stressful and it's important not to make mistakes that could turn a fun day into a nightmere, so here are key mistakes to avoid to have a smooth movi`,
    image: BRAND_IMAGES.crewCarryingFurniture,
    readTime: "3 min read",
  },
  {
    slug: "choosing-the-best-storage-unit-for-you",
    title: `Choosing the Best Storage Unit For Your Needs`,
    date: "November 7, 2017",
    category: "Storage",
    excerpt: `Storage units are handy when you need a place to store things you don’t use frequently, giving you a place to safely store furniture, heirlooms, and more.`,
    image: BRAND_IMAGES.warehouseInterior,
    readTime: "3 min read",
  },
  {
    slug: "get-your-security-deposit-back",
    title: `7 Steps To Get Your Security Deposit Back`,
    date: "July 28, 2016",
    category: "Moving Tips",
    excerpt: `Moving to a new Redmond apartment? Here's how you can get you deposit back with a few practical steps! Your Redmond moving company is here to help. `,
    image: BRAND_IMAGES.crewDoorway1,
    readTime: "4 min read",
  },
  {
    slug: "how-to-efficiently-pack-a-storage-container",
    title: `How to Efficiently Pack A Storage Container`,
    date: "August 17, 2018",
    category: "Packing Tips",
    excerpt: `Looking for ways to maximize the space in your storage container? Explore our four helpful tips to efficiently and securely pack your belongings for storage.`,
    image: BRAND_IMAGES.truckResidentialBuilding,
    readTime: "3 min read",
  },
  {
    slug: "7-tips-make-move-less-stressful",
    title: `7 Tips To Make Your Move Less Stressful`,
    date: "July 18, 2017",
    category: "Moving Costs",
    excerpt: `Moving is a stressful process. Packing boxes with your items, loading into a moving truck, and unpacking puts a lot of stress on you and your family. Read our 7`,
    image: BRAND_IMAGES.crewEntryway3,
    readTime: "4 min read",
  },
  {
    slug: "packing-like-a-pro-5-tips-to-make-moving-a-breeze",
    title: `Packing Like a Pro: 5 Tips to Make Moving a Breeze`,
    date: "July 18, 2016",
    category: "Packing Tips",
    excerpt: `When it comes to moving, packing up all your belongings can be a hassle. Here are 5 packing tips to keep your stuff safe and organized. `,
    image: BRAND_IMAGES.crewWrappingEntryway,
    readTime: "3 min read",
  },
  {
    slug: "how-to-pack-a-storage-unit",
    title: `How to Pack and Organize a Storage Unit | Best Tips for Ease of Access`,
    date: "March 27, 2020",
    category: "Packing Tips",
    excerpt: `If this is your first time packing a storage unit, our moving experts here at On The Go Moving have compiled a list of 6 helpful, organizational tips for you.`,
    image: BRAND_IMAGES.warehouseInterior,
    readTime: "5 min read",
  },
  {
    slug: "storage-unit-prices",
    title: `Storage Unit Prices`,
    date: "July 16, 2021",
    category: "Moving Costs",
    excerpt: `Learn more about storage unit prices and what solutions are available to you. Get in touch with On The Go Moving today, for more details.`,
    image: BRAND_IMAGES.teamMemberWarehouse,
    readTime: "4 min read",
  },
  {
    slug: "leave-behind-moving-5-ways-declutter-house",
    title: `What to Leave Behind When Moving: 5 Ways to Declutter Your House`,
    date: "June 26, 2017",
    category: "Moving Tips",
    excerpt: `Take the process of moving as an opportunity to rid yourself of the clutter that has collected over the years and start fresh. Whether it’s your first big move `,
    image: BRAND_IMAGES.crewFloorProtection1,
    readTime: "3 min read",
  },
  {
    slug: "fill-two-needs-with-one-deed-moving-and-storage",
    title: `Fill Two Needs with One Deed: Moving and Storage`,
    date: "August 12, 2016",
    category: "Storage",
    excerpt: `Save time and money by hiring moving and storage services from On The Go. Our experienced staff can make your residential move affordable and stress-free. `,
    image: BRAND_IMAGES.warehouseCrates,
    readTime: "3 min read",
  },
  {
    slug: "packing-fragile-items",
    title: `Packing Fragile Items Prior to Moving`,
    date: "October 28, 2022",
    category: "Packing Tips",
    excerpt: `Learn about Packing Fragile Items prior to moving, from the cost and types of damages of the items. Give On The Go Moving a call today to learn more.`,
    image: BRAND_IMAGES.crewWrappingFurniture,
    readTime: "4 min read",
  },
  {
    slug: "best-tips-for-winter-moving",
    title: `Best Tips for Winter Moving`,
    date: "March 16, 2022",
    category: "Moving Costs",
    excerpt: `Are you planning for winter moving? Find out all of our best moving suggestions to make the process go more smoothly. Visit us now.`,
    image: BRAND_IMAGES.truckResidentialStreet,
    readTime: "3 min read",
  },
  {
    slug: "how-to-pack-a-car-for-moving",
    title: `Helpful Tips On How to Pack A Car for Moving`,
    date: "January 16, 2018",
    category: "Packing Tips",
    excerpt: `Explore helpful tips on how to pack a car for moving, including tricks and strategies for how you can safely and effectively pack your car for your move.`,
    image: BRAND_IMAGES.customerHandshake,
    readTime: "4 min read",
  },
  {
    slug: "white-glove-delivery",
    title: `What Is White Glove Delivery? Service & Definition`,
    date: "March 26, 2023",
    category: "Moving Tips",
    excerpt: `We’ll explain white glove delivery for you. Follow our guide & see what relocation services entail. Contact us & learn what our moving experts can accomplish!`,
    image: BRAND_IMAGES.crewBanisterWrap,
    readTime: "4 min read",
  },
  {
    slug: "benefits-of-climate-controlled-storage",
    title: `8 Reasons Climate Controlled Storage Units Are Best For Indoor Storage`,
    date: "March 30, 2017",
    category: "Storage",
    excerpt: `Climate-controlled storage provides many improvements over outdoor storage, and some items even require climate-controlled vaults over outdoor units. Below we’l`,
    image: BRAND_IMAGES.warehouseCratesAlt,
    readTime: "5 min read",
  },
  {
    slug: "are-you-hiring-a-certified-moving-company",
    title: `Are You Hiring a Certified Moving Company?`,
    date: "November 18, 2016",
    category: "Moving Tips",
    excerpt: `If you are hiring a moving company, it's vital to make sure they are fully certified. Here's exactly how you can know and get your home moved properly.`,
    image: BRAND_IMAGES.truckProfessionalLot,
    readTime: "3 min read",
  },
  {
    slug: "tricks-to-unpack-your-home-in-2-days",
    title: `How To Unpack After Moving In 2 Days`,
    date: "October 21, 2016",
    category: "Packing Tips",
    excerpt: `How to unpack after a move can be crucial, if you don’t do it the right way it can turn in a daunting experience. Follow our tips to unpack quickly & smoothly!`,
    image: BRAND_IMAGES.crewDoorway2,
    readTime: "3 min read",
  },
  {
    slug: "move-in-date",
    title: `Move In Date: How To Match Apartment Dates For My Move`,
    date: "October 14, 2016",
    category: "Moving Tips",
    excerpt: `Your move in & lease date can be the most important part of the contract. Let’s go over differences and similarities to negotiate.`,
    image: BRAND_IMAGES.crewDoorway3,
    readTime: "3 min read",
  },
  {
    slug: "7-of-the-best-places-to-live-in-the-u-s",
    title: `7 of the Best Places to Live in the U.S.`,
    date: "November 6, 2017",
    category: "Local Guides",
    excerpt: `When it comes to the best cities to live in the U.S., there are so many great places to be. Let's take a look at 7 of the best cities to live in the U.S.`,
    image: BRAND_IMAGES.crewDoorway2,
    readTime: "4 min read",
  },
  {
    slug: "how-to-make-a-new-apartment-feel-like-home",
    title: `How To Make A New Apartment Feel Like Home`,
    date: "April 1, 2022",
    category: "Specialty Moving",
    excerpt: `Are you looking for the ideas on how to make a new apartment feel like home? On the Go Moving assists you by providing the best suggestions.`,
    image: BRAND_IMAGES.crewDoorway3,
    readTime: "3 min read",
  },
  {
    slug: "top-tips-on-how-to-make-a-house-a-home",
    title: `Top Tips on How to Make a House a Home`,
    date: "March 24, 2022",
    category: "Moving Costs",
    excerpt: `Looking for the best tips on how to make a house a home? This post by On The Go Moving can help you get professional assistance. Click here now!`,
    image: BRAND_IMAGES.crewCustomerCommercial,
    readTime: "4 min read",
  },
  {
    slug: "moving-into-new-house",
    title: `11 Tips To Do First After Moving Into A New House`,
    date: "November 30, 2019",
    category: "Moving Tips",
    excerpt: `Congratuations on your new home! Now what? Explore the first 11 things to do after moving into your new house so you can feel comfortable in your new home as so`,
    image: BRAND_IMAGES.crewDoorway1,
    readTime: "5 min read",
  },
  {
    slug: "hiring-professional-movers-vs-moving-yourself",
    title: `What To Know About Hiring Professional Movers vs Moving Yourself`,
    date: "December 1, 2021",
    category: "Moving Tips",
    excerpt: `Have trouble between hiring a moving company or DIY for moving? Read now for more information about the pros and cons of hiring and DIY moving.`,
    image: BRAND_IMAGES.customerHandshake,
    readTime: "3 min read",
  },
  {
    slug: "our-new-ultimate-moving-guide-is-now-available",
    title: `Our New Ultimate Moving Guide Is Now Available!`,
    date: "July 28, 2015",
    category: "Moving Tips",
    excerpt: `To make the moving process even easier, we have created an easy to follow, step-by-step guide that families can use to plan and prepare for their moving day.`,
    image: BRAND_IMAGES.truckProfessionalLot,
    readTime: "3 min read",
  },
  {
    slug: "housewarming-party-ideas-and-food",
    title: `Ideas For The Ultimate Housewarming Party | Planning Food, Themes, Games, & Drinks`,
    date: "September 27, 2019",
    category: "Specialty Moving",
    excerpt: `Planning a housewarming party doesn’t need to be stress-inducing at all. Rather it gives you a fun chance to whip out your creative skills and introduce people.`,
    image: BRAND_IMAGES.crewEntryway1,
    readTime: "5 min read",
  },
  {
    slug: "first-time-moving-heres-simple-checklist",
    title: `Checklist: First Time Moving Out | Tips For Packing Room By Room`,
    date: "August 22, 2017",
    category: "Moving Tips",
    excerpt: `Now that you’re ready to move out for the first time, the next step is to get organized and plan your move down to the smallest detail. To make things easier fo`,
    image: BRAND_IMAGES.crewEntryway3,
    readTime: "3 min read",
  },
  {
    slug: "6-helpful-house-moving-tips-for-people-with-disabilities",
    title: `6 Helpful House Moving Tips for People with Disabilities`,
    date: "November 28, 2017",
    category: "Moving Costs",
    excerpt: `Moving is made more difficult if you or someone who you are moving has a disability. Here's a few helpful house moving tips for people with disabilities.`,
    image: BRAND_IMAGES.crewLoadingTruckRamp,
    readTime: "3 min read",
  },
  {
    slug: "4-ways-professional-movers-can-make-relocation-breeze",
    title: `4 Ways Professional Movers Can Make Your Relocation a Breeze`,
    date: "July 25, 2017",
    category: "Moving Tips",
    excerpt: `When the time comes to move to a new home, whether you are moving to a new city or a new state, hiring professional movers can make your relocation process much`,
    image: BRAND_IMAGES.crewCustomerCommercial,
    readTime: "3 min read",
  },
  {
    slug: "3-things-to-expect-when-moving-your-house-across-town",
    title: `Moving Across Town: What To Expect and How To Be Prepared`,
    date: "February 26, 2016",
    category: "Moving Tips",
    excerpt: `Although it may seem like a short distance, a move across town can be a lot of work. On The Go Moving shares 3 things to expect when moving across town.`,
    image: BRAND_IMAGES.crewCarryingFurniture,
    readTime: "3 min read",
  },
  {
    slug: "cheap-packing-materials-for-a-move",
    title: `What Cheap Packing Materials Can You Use for a Move?`,
    date: "February 27, 2018",
    category: "Packing Tips",
    excerpt: `Moving can be an expensive process, but there are ways to cut costs – for example, by using cheap packing materials for your move. Discover the unusual items yo`,
    image: BRAND_IMAGES.crewWrappingEntryway,
    readTime: "3 min read",
  },
  {
    slug: "how-to-pack-dishes",
    title: `How To Pack Dishes | Kitchenware, Pots and Pans, and Glasses`,
    date: "September 27, 2019",
    category: "Packing Tips",
    excerpt: `The last thing you want is breaking any of your dishes while moving, that's why we've compiled a 5 step process to packing your dishes safely and securely.`,
    image: BRAND_IMAGES.crewWrappingFurniture,
    readTime: "3 min read",
  },
  {
    slug: "how-much-do-movers-cost",
    title: `What Does a Local Move Cost? Typical Ranges by Home Size`,
    date: "2024-01-01",
    category: "Moving Costs",
    excerpt: `How Much Do Movers Cost`,
    image: BRAND_IMAGES.customerHandshake,
    readTime: "3 min read",
  },
  {
    slug: "moving-over-the-holidays-how-to-be-successful-during-holiday-relocation-2",
    title: `Moving Over the Holidays: How to Be Successful During Holiday Relocation`,
    date: "November 24, 2016",
    category: "Moving Tips",
    excerpt: `Moving over the holidays can be stressful. Here's how you can manage a move over the holidays and enjoy your new residence in peace.`,
    image: BRAND_IMAGES.truckResidentialStreet,
    readTime: "5 min read",
  },
  {
    slug: "make-moving-in-with-your-partner-easy",
    title: `Moving In Together: 4 Important Questions Before You Move`,
    date: "February 14, 2018",
    category: "Specialty Moving",
    excerpt: `When you move in with your partner, you create the ideal environment for lots of fun times and good memories. However, it's important to be prepared so as to av`,
    image: BRAND_IMAGES.crewEntryway3,
    readTime: "4 min read",
  },
  {
    slug: "how-to-find-the-best-temporary-storage-units-in-your-area",
    title: `How to Find the Best Temporary Storage Units in Your Area`,
    date: "January 18, 2019",
    category: "Storage",
    excerpt: `If you're preparing for a move, you are probably realizing that you have more belongings than you thought. Temporary storage can help you organize and keep safe`,
    image: BRAND_IMAGES.warehouseCrates,
    readTime: "3 min read",
  },
  {
    slug: "importance-of-knowing-where-to-get-fast-moving-services",
    title: `Importance of Knowing Where to Get Fast Moving Services`,
    date: "August 18, 2016",
    category: "Moving Tips",
    excerpt: `There are many reasons you might need fast moving services in the Seattle area. Here's a list of emergency situations, how to solve them, and who to call. `,
    image: BRAND_IMAGES.crewLoadingTruckRamp,
    readTime: "3 min read",
  },
  {
    slug: "declutter-your-home-7-items-you-need-to-ditch-before-your-move",
    title: `Declutter Your Home: 7 Items You Need to Ditch Before Your Move`,
    date: "July 23, 2018",
    category: "Moving Tips",
    excerpt: `Trying to declutter your home the day of your move can be a taxing task. Here are seven items you can toss before you move so you can eliminate stress in the mo`,
    image: BRAND_IMAGES.crewRollingRug,
    readTime: "3 min read",
  },
  {
    slug: "decluttering-tricks-before-you-move",
    title: `Checklist: 7 Questions To Ask When You Declutter Your Home`,
    date: "September 8, 2016",
    category: "Moving Tips",
    excerpt: `If you are preparing for a big move, the moving and storage process can be tough. Here's how you can sort through your belongings and make the move easier:`,
    image: BRAND_IMAGES.crewRollingRug,
    readTime: "4 min read",
  },
  {
    slug: "on-the-go-moving-what-we-do-and-why",
    title: `The On The Go Moving Story: Here’s What We do and Why`,
    date: "October 6, 2014",
    category: "Moving Tips",
    excerpt: `Moving is a huge transition. A new place, a new life, a new situation – there is a lot of change involved in moving and that can result in added emotions and co`,
    image: BRAND_IMAGES.jasonPortrait,
    readTime: "3 min read",
  },
  {
    slug: "why-should-you-hire-moving-and-storage-services-at-the-same-time",
    title: `Why Should You Hire Moving and Storage Services at the Same Time?`,
    date: "December 17, 2018",
    category: "Storage",
    excerpt: `Moving is a complicated and stressful experience. However, by hiring professional moving and storage services to assist in your move, you can significantly redu`,
    image: BRAND_IMAGES.crewForklift,
    readTime: "4 min read",
  },
  {
    slug: "what-not-to-pack-when-moving-non-allowable-items-explained",
    title: `What Not to Pack When Moving: Non-Allowable Items Explained`,
    date: "August 7, 2018",
    category: "Packing Tips",
    excerpt: `A professional moving company will transport anything that you ask them to, right? Actually, most moving companies have certain items that they cannot transport`,
    image: BRAND_IMAGES.crewWrappingOffice,
    readTime: "3 min read",
  },
  {
    slug: "how-much-do-you-tip-movers",
    title: `How Much To Tip Movers?`,
    date: "March 18, 2021",
    category: "Moving Costs",
    excerpt: `Do You Need to Tip Movers? Here are five things to consider when deciding how much to tip movers. Read more on this article!`,
    image: BRAND_IMAGES.crewLoadingTruckRamp,
    readTime: "7 min read",
  },
  {
    slug: "moving-with-pets-7-tips",
    title: `7 Tips for Moving with Pets Successfully`,
    date: "January 30, 2018",
    category: "Moving Costs",
    excerpt: `If you have pets and you're preparing to move, you move just got a little more complicated. However, moving with pets doesn't have to be difficult, and we've as`,
    image: BRAND_IMAGES.crewFrontDoorExit,
    readTime: "4 min read",
  },
  {
    slug: "simplify-move-turn-move-road-trip",
    title: `How to Simplify Your Move: Turn Your Move Into a Road Trip`,
    date: "June 5, 2017",
    category: "Moving Tips",
    excerpt: `Moving from one place to another presents unique challenges to your family, especially when the move is a far one. However, there are several things you can do `,
    image: BRAND_IMAGES.crewCarryingFurniture,
    readTime: "4 min read",
  },
  {
    slug: "packrat-panic-tips-to-moving-when-youre-a-packrat",
    title: `PackRat Panic - Tips to Moving When You’re a PackRat`,
    date: "October 27, 2016",
    category: "Packing Tips",
    excerpt: `When it comes to moving, some are overwhelmed by the amount of belongings needed to be packed. Here's how anyone can move quickly, even as a packrat. `,
    image: BRAND_IMAGES.crewCarryingUpRamp,
    readTime: "4 min read",
  },
  {
    slug: "organizing-small-spaces",
    title: `14 Organizing Tips For Maximizing A Small Space`,
    date: "September 27, 2019",
    category: "Moving Tips",
    excerpt: `Minimalizing and moving to smaller homes is a growing movement in the 21st Century. How do you organize and maximize the space in your house?`,
    image: BRAND_IMAGES.crewCarryingOut,
    readTime: "6 min read",
  },
  {
    slug: "would-you-trust-a-stranger-with-everything-you-own",
    title: `Would You Trust a Stranger with Everything You Own?`,
    date: "March 3, 2016",
    category: "Moving Tips",
    excerpt: `On The Go Moving and Storage shares tips to help you successfully hire a Seattle moving company you can rely on and trust for your next move.`,
    image: BRAND_IMAGES.crewFrontDoorExit,
    readTime: "3 min read",
  },
  {
    slug: "covid-19-on-the-go-ensures-your-move-is-healthy-and-safe",
    title: `COVID-19: On The Go Follows CDC Guidelines for Healthy Moves`,
    date: "March 12, 2020",
    category: "Specialty Moving",
    excerpt: `Moving during COVID-19 can feel stressful. That's we why we've implemented strict health precautions to keep our customers safe and their move smooth.`,
    image: BRAND_IMAGES.crewLoadingTruckRamp,
    readTime: "3 min read",
  },
  {
    slug: "5-tips-to-go-green-for-your-upcoming-kirkland-move",
    title: `5 Tips to Go Green for Your Upcoming Kirkland Move`,
    date: "June 15, 2016",
    category: "Moving Costs",
    excerpt: `Kirkland moving company On The Go Moving and Storage shares tips to go green with your upcoming Kirkland move.`,
    image: BRAND_IMAGES.truckKirklandHouse,
    readTime: "3 min read",
  },
  {
    slug: "how-to-choose-the-best-neighborhood-when-moving-to-a-new-city",
    title: `How to Choose the Best Neighborhood When Moving to a New City`,
    date: "April 4, 2019",
    category: "Local Guides",
    excerpt: `What should you take into consideration when making the decision to move? Read the most important factors to consider when choosing to live in a city.`,
    image: BRAND_IMAGES.truckSeattleSkyline,
    readTime: "3 min read",
  },
  {
    slug: "moving-101-how-to-pack-your-electronics-for-moving",
    title: `Moving 101: How to Pack Your Electronics for Moving`,
    date: "January 17, 2017",
    category: "Packing Tips",
    excerpt: `If you're wondering how to pack your electronics for moving, here's how to safely transport your desk to the new home.`,
    image: BRAND_IMAGES.truckSeattleSkyline,
    readTime: "4 min read",
  },
  {
    slug: "5-questions-before-hiring-commercial-moving-company",
    title: `Top Questions to Ask Moving Companies`,
    date: "September 23, 2015",
    category: "Commercial Moving",
    excerpt: `On The Go Moving encourages businesses to look for these qualities in a commercial moving company before hiring them to perform the move.`,
    image: BRAND_IMAGES.officeMoveAction,
    readTime: "3 min read",
  },
  {
    slug: "moving-hacks",
    title: `25 Clever Moving Hacks and Advice to Make Your Move Less Stressful`,
    date: "August 8, 2023",
    category: "Moving Tips",
    excerpt: `With the moving hacks here go for a better and faster move. Read to find some great moving tips to avoid stress and save money. Contact us today!`,
    image: BRAND_IMAGES.crewCarryingUpRamp,
    readTime: "3 min read",
  },
  {
    slug: "bellevue-washington-movers",
    title: `Everything You Need To Know About Bellevue Washington Movers`,
    date: "February 25, 2023",
    category: "Local Guides",
    excerpt: `Learn everything you need to know about the Bellevue Washing Movers. Give On The Go Moving & Storage a call today to learn more about their service.`,
    image: BRAND_IMAGES.truckBellevueSkyline,
    readTime: "3 min read",
  },
  {
    slug: "10-expert-tips-to-make-your-winter-move-an-easier-mission",
    title: `10 Expert Tips For Easier Moving In The Winter`,
    date: "December 20, 2018",
    category: "Moving Costs",
    excerpt: `Moving in the winter can actually be great timing, check out our tips to make your life easier. Make your plans and prepping ahead and let us help you handle th`,
    image: BRAND_IMAGES.truckBellevueSkyline,
    readTime: "4 min read",
  },
  {
    slug: "the-benefits-of-hiring-moving-and-storage-services-at-the-same-time",
    title: `The Benefits of Hiring Moving and Storage Services at the Same Time`,
    date: "December 12, 2017",
    category: "Storage",
    excerpt: `Renting a storage space can serve the dual purpose of clearing clutter and providing you a safe place to store important belongings during and after the move. I`,
    image: BRAND_IMAGES.storageWarehouse,
    readTime: "3 min read",
  },
  {
    slug: "10-things-to-know-for-moving-during-covid",
    title: `Essential Things to Know When Moving During Covid`,
    date: "March 24, 2022",
    category: "Moving Tips",
    excerpt: `Are you planning for moving during covid? To make the experience go more smoothly, here are all of our excellent moving tips.`,
    image: BRAND_IMAGES.crewStaircaseExit,
    readTime: "3 min read",
  },
  {
    slug: "10-things-to-remember-when-moving",
    title: `10 Things to Remember when Moving`,
    date: "April 21, 2022",
    category: "Moving Tips",
    excerpt: `Get On The Moving’s blog article on the list of things to remember when moving and after that you don't forget anything.`,
    image: BRAND_IMAGES.crewOverheadEntrance,
    readTime: "4 min read",
  },
  {
    slug: "10-moving-tips-for-making-your-family",
    title: `Top 10 Tips for Moving Family Across Country`,
    date: "May 16, 2017",
    category: "Moving Costs",
    excerpt: `Are you going to move with your family soon? Get this article from On the Go Moving company and make sure nothing is overlooked while relocating.`,
    image: BRAND_IMAGES.truckProfessionalLot,
    readTime: "4 min read",
  },
  {
    slug: "10-tips-things-most-families-forget-during-move",
    title: `10 Tips: Things Most Families Forget During a Move`,
    date: "November 15, 2017",
    category: "Moving Costs",
    excerpt: `Moving is a stressful event, especially when you're trying to move a family. Take a look at these 10 moving tips to make your move a lot less stressful.`,
    image: BRAND_IMAGES.truckKirklandHouse,
    readTime: "4 min read",
  },
  {
    slug: "12-modern-interior-design-tips-for-decorating-small-spaces",
    title: `12 Interior Design Tips For Small Spaces - Modern Decoration`,
    date: "May 2, 2017",
    category: "Moving Costs",
    excerpt: `Use these interior design tips for small spaces and make a dream out of any small home. Learn some decorating techniques that make your space larger and clutter`,
    image: BRAND_IMAGES.truckBrickBuilding,
    readTime: "4 min read",
  },
  {
    slug: "11-tips-for-an-easy-diy-move",
    title: `11 Tips For An Easy DIY Move You Should Know`,
    date: "December 1, 2021",
    category: "Moving Costs",
    excerpt: `There are a lot of ways to simplify your DIY move. Here are our top 11 tips for a smooth and easy DIY move. Check out and read now for more information.`,
    image: BRAND_IMAGES.truckResidentialBuilding,
    readTime: "4 min read",
  },
  {
    slug: "10-things-you-need-when-moving-into-your-new-home",
    title: `10 Things You Need When Moving Into Your New Home`,
    date: "March 19, 2018",
    category: "Moving Tips",
    excerpt: `Are you getting ready to move into a new house, but are not sure if you have everything you need? We've collected an important list of 10 things you may need to`,
    image: BRAND_IMAGES.threeCrewLoadingTruck,
    readTime: "4 min read",
  },
  {
    slug: "advantages-of-warehousing",
    title: `Benefits & Advantages of Warehousing`,
    date: "March 26, 2023",
    category: "Moving Tips",
    excerpt: `The advantages of warehousing benefit businesses from reduced delivery time to storing benefits. Learn how warehousing helps proprietors & consumers!`,
    image: BRAND_IMAGES.brandedTruck,
    readTime: "4 min read",
  },
  {
    slug: "15-signs-of-a-worst-moving-company",
    title: `15 Signs of a Worst Moving Company`,
    date: "May 30, 2022",
    category: "Moving Tips",
    excerpt: `Read On The Moving’s blog article about the list of signs of the worst moving companies you should remember before moving.`,
    image: BRAND_IMAGES.threeCrewRampLoading,
    readTime: "3 min read",
  },
  {
    slug: "make-your-move-easy-temporary-storage",
    title: `Temporary Storage Between Moves For Easy Moving`,
    date: "June 19, 2018",
    category: "Storage",
    excerpt: `Finding temporary storage between moves or other short term solutions shouldn’t be difficult. Learn about the options you should keep in mind and the solutions `,
    image: BRAND_IMAGES.storageWarehouse,
    readTime: "4 min read",
  },
  {
    slug: "reasons-to-hire-professional-piano-movers",
    title: `Why Professional Piano Movers Are Essential for a Safe Move`,
    date: "April 30, 2025",
    category: "Specialty Moving",
    excerpt: `Discover the reasons why hiring professional piano movers is essential for a safe & damage-free move. Protect your investment with expert service.`,
    image: BRAND_IMAGES.crewRamp,
    readTime: "3 min read",
  },
  {
    slug: "what-to-pack-first-moving",
    title: `Tips For What To Pack First When You're Moving`,
    date: "January 11, 2020",
    category: "Packing Tips",
    excerpt: `Deciding to what to pack first can feel like a daunting task. To help your move go smoothly and stress-free, we've complied a step by step list.`,
    image: BRAND_IMAGES.truckResidentialStreet,
    readTime: "5 min read",
  },
  {
    slug: "how-to-meet-your-neighbors",
    title: `How To Meet Your New Neighbors | 7 Non-Awkward Tips For Introducing Yourself`,
    date: "September 27, 2019",
    category: "Moving Tips",
    excerpt: `A professional moving company will take care of all the packing, loading, and actual moving freeing you up to meet the neighbors!`,
    image: BRAND_IMAGES.crewHoodieAtTruck,
    readTime: "4 min read",
  },
  {
    slug: "what-to-expect-when-moving-during-the-off-season",
    title: `What to Expect When Moving During the Off-Season`,
    date: "December 20, 2024",
    category: "Moving Tips",
    excerpt: `Discover off-season moving benefits, including flexible scheduling and savings. Get practical moving during winter tips to make any relocation stress-free.`,
    image: BRAND_IMAGES.crewStaircase1,
    readTime: "3 min read",
  },
  {
    slug: "how-many-trips-does-a-local-move-really-take",
    title: `How Many Trips Does a Local Move Really Take?`,
    date: "December 21, 2024",
    category: "Moving Tips",
    excerpt: `Planning a move? Discover how many trips for a local move it takes and learn tips to minimize moving truck trips for local moves efficiently`,
    image: BRAND_IMAGES.crewEntryway1,
    readTime: "3 min read",
  },
  {
    slug: "cost-saving-strategies-for-a-budget-friendly-move",
    title: `Cost-Saving Strategies for a Budget-Friendly Move`,
    date: "December 21, 2024",
    category: "Moving Costs",
    excerpt: `Save money with budget moving tips like sourcing free supplies and choosing the right date. Learn affordable moving strategies for stress-free relocation.`,
    image: BRAND_IMAGES.customerHandshake,
    readTime: "3 min read",
  },
  {
    slug: "furniture-storage-units",
    title: `Finding The Furniture Storage Units For Long-Term and Short-Term Storage`,
    date: "March 21, 2024",
    category: "Storage",
    excerpt: `When moving, furniture storage units are an excellent way to keep your furniture accessible, safe, and secure. Contact On The Go Moving, for professional assist`,
    image: BRAND_IMAGES.crewCarryingFurniture,
    readTime: "3 min read",
  },
  {
    slug: "how-to-pack-for-moving",
    title: `How To Pack For A Move?`,
    date: "April 17, 2024",
    category: "Packing Tips",
    excerpt: `For smooth moving, you need to make sure you have the right packing supplies and expert tips on how to pack for a move to get your belongings packed safely and `,
    image: BRAND_IMAGES.crewCustomerCommercial,
    readTime: "4 min read",
  },
  {
    slug: "top-7-tips-for-a-smooth-move-a-moving-companys-recommendations-for-your-moving-day",
    title: `Top 7 Moving Day Tips: How To Enjoy Your Moving Day`,
    date: "March 16, 2015",
    category: "Moving Costs",
    excerpt: `When it comes to your moving day, you need all the help you can get. In this article we offer great moving tips from the pros on packing, moving`,
    image: BRAND_IMAGES.crewLoadingTruckRamp,
    readTime: "5 min read",
  },
  {
    slug: "movers-guide-sammamish",
    title: `Movers Guide in Sammamish`,
    date: "February 25, 2023",
    category: "Moving Tips",
    excerpt: `Want to know the Movers Guide in Sammamish and how to pay for a move once you the budget? Give On The Go Moving a call today to learn more.`,
    image: BRAND_IMAGES.crewCustomerCommercial,
    readTime: "3 min read",
  },
  {
    slug: "taking-back-your-house-9-organizational-tips-for-small-spaces",
    title: `Taking Back Your House: 9 Organizational Tips for Small Spaces`,
    date: "January 23, 2019",
    category: "Moving Costs",
    excerpt: `Is your home crowded and cluttered? These 9 home organization tips for small spaces will help you reclaim your space and relieve the stress of a cluttered house`,
    image: BRAND_IMAGES.crewCarryingUpRamp,
    readTime: "3 min read",
  },
  {
    slug: "9-common-moving-mistakes-and-tips-on-how-to-avoid-them",
    title: `9 Common Moving Mistakes and Tips on How to Avoid Them`,
    date: "December 15, 2025",
    category: "Moving Costs",
    excerpt: `Moving can stressful and it can be easy to forget things or let things slip through cracks, here are 9 common mistakes everyone makes and how to avoid them.`,
    image: BRAND_IMAGES.truckSeattleSkyline,
    readTime: "4 min read",
  },
  {
    slug: "how-to-throw-a-housewarming-party-in-15-easy-steps",
    title: `How to Throw a Housewarming Party in 15 Easy Steps`,
    date: "October 25, 2018",
    category: "Specialty Moving",
    excerpt: `Moving into a new neighborhood is a great opportunity to get to know your neighbors and make new friends. Use these 15 steps for throwing a housewarming party t`,
    image: BRAND_IMAGES.crewEntryway2,
    readTime: "4 min read",
  },
  {
    slug: "6-tips-for-meeting-your-neighbors-after-a-move",
    title: `6 Tips For Meeting Your Neighbors After A Move`,
    date: "October 17, 2018",
    category: "Moving Costs",
    excerpt: `Moving into a new neighborhood can be difficult, as you are forced to make new friends and neighbors. However, with these 6 tips, meeting your neighbors can be `,
    image: BRAND_IMAGES.truckBellevueSkyline,
    readTime: "3 min read",
  },
  {
    slug: "mercer-island-movers",
    title: `Mercer Island Movers – On The Go Moving & Storage`,
    date: "2024-01-01",
    category: "Moving Tips",
    excerpt: `Licensed & insured Mercer Island movers. Full-service residential, commercial & storage solutions in Mercer Island, WA. Request your free quote today!”`,
    image: BRAND_IMAGES.customerHandshake,
    readTime: "3 min read",
  },
  {
    slug: "how-to-pack-your-clothes-for-a-move",
    title: `How To Pack Your Clothes For A Move`,
    date: "February 15, 2019",
    category: "Packing Tips",
    excerpt: `If you're preparing to move, packing your clothes can be is a good way to get the ball rolling for the whole packing process. Utilize these moving hacks to make`,
    image: BRAND_IMAGES.truckProfessionalLot,
    readTime: "4 min read",
  },
  {
    slug: "4-things-you-didnt-know-about-kirkland",
    title: `4 Things You Didn't Know About Kirkland`,
    date: "May 13, 2016",
    category: "Local Guides",
    excerpt: `Kirkland is a beautiful and interesting place to live. Here are four things that you may not know about the city from On The Go Kirkland moving company:`,
    image: BRAND_IMAGES.truckKirklandHouse,
    readTime: "3 min read",
  },
  {
    slug: "5-small-space-decorating-tips",
    title: `5 Small Space Decorating Tips`,
    date: "July 22, 2016",
    category: "Moving Costs",
    excerpt: `Modern apartments are getting smaller every year. Here's how you can make the most of your living space with 5 decorating tips for small apartments. `,
    image: BRAND_IMAGES.truckKirklandHouse,
    readTime: "3 min read",
  },
  {
    slug: "7-reasons-why-never-use-a-moving-company",
    title: `7 Reasons Why you should Never Use a Moving Company`,
    date: "October 9, 2015",
    category: "Moving Tips",
    excerpt: `On The Go Moving reveals seven major and ironic reasons why Redmond families should never hire a moving company to assist with their move.`,
    image: BRAND_IMAGES.crewEntryway3,
    readTime: "4 min read",
  },
  {
    slug: "apartment-vs-house",
    title: `Apartment vs House: How To Move Into A New Space`,
    date: "August 25, 2016",
    category: "Specialty Moving",
    excerpt: `Moving to an apartment is different than a large residential house, and each different situation may demand different moving services.`,
    image: BRAND_IMAGES.crewDoorway1,
    readTime: "3 min read",
  },
  {
    slug: "packing-tips-easy-steps-to-packing-your-kitchen",
    title: `Packing Tips: Easy Steps to Packing Your Kitchen`,
    date: "September 23, 2016",
    category: "Packing Tips",
    excerpt: `Packing your kitchen can be one of the most time-consuming parts of your move. Here are some tips and tricks to help the process go smoothly and quickly.`,
    image: BRAND_IMAGES.truckBrickBuilding,
    readTime: "3 min read",
  },
  {
    slug: "moving-tips-the-right-way-to-pack-your-kids-room",
    title: `Moving Tips: The Right Way to Pack Your Kid's Room`,
    date: "December 21, 2016",
    category: "Packing Tips",
    excerpt: `Moving can be a challenging process, and it's important to keep your children in mind during this busy time. Here are some helpful moving tips to help. `,
    image: BRAND_IMAGES.truckResidentialBuilding,
    readTime: "4 min read",
  },
  {
    slug: "the-first-10-things-you-need-to-do-when-youve-moved-into-a-new-place",
    title: `Checklist: 10 First Things To Do After Moving Into A New House`,
    date: "November 11, 2016",
    category: "Moving Tips",
    excerpt: `Unpacking after the big move can be overwhelming. Here are some quick unpacking tips for how you can move into your new home stress-free and on time.`,
    image: BRAND_IMAGES.crewDoorway2,
    readTime: "3 min read",
  },
  {
    slug: "tips-for-getting-comfortable-in-your-new-home",
    title: `Tips for Getting Comfortable in Your New Home`,
    date: "April 20, 2017",
    category: "Moving Costs",
    excerpt: `Moving into a new house is exciting, but it can also be overwhelming. This is especially true if you are a first-time homeowner. Turn your new house into a home`,
    image: BRAND_IMAGES.truckResidentialStreet,
    readTime: "3 min read",
  },
  {
    slug: "know-moving-rental",
    title: `Checklist: What To Know Before You Move Into Your New Rental`,
    date: "September 12, 2017",
    category: "Moving Tips",
    excerpt: `When entering into a long term agreement like a lease on a house or apartment, it’s good to be aware of what could potentially go wrong when basic precautions a`,
    image: BRAND_IMAGES.crewDoorway3,
    readTime: "4 min read",
  },
  {
    slug: "homeward-bound-moving-with-pets",
    title: `Homeward Bound: Moving With Pets`,
    date: "May 11, 2017",
    category: "Moving Tips",
    excerpt: `Moving across town or even across the country with pets is easier than it appears. The key is to prepare adequately for the move. Even if you’re doing this at t`,
    image: BRAND_IMAGES.crewCarryingFurniture,
    readTime: "3 min read",
  },
  {
    slug: "6-simple-ways-to-make-sure-you-get-your-rental-deposit-returned",
    title: `6 Simple Tips to Make Sure You Get Your Rental Deposit Returned`,
    date: "October 12, 2017",
    category: "Moving Tips",
    excerpt: `When the time comes to move out of a rental, there is one issue that embitters landlord-tenant relationships: the return of the security deposit.`,
    image: BRAND_IMAGES.crewCarryingOut,
    readTime: "4 min read",
  },
  {
    slug: "pack-move-packing-tips-kids-room",
    title: `Moving With Kids: Packing Tips For Your Kid’s Room`,
    date: "September 19, 2017",
    category: "Packing Tips",
    excerpt: `There are several packing tips you can use to make packing up your kids’ rooms as smooth and pain-free as possible. It takes work, but your busy schedule also p`,
    image: BRAND_IMAGES.customerHandshake,
    readTime: "4 min read",
  },
  {
    slug: "the-3-best-ways-to-pack-clothes-for-a-move",
    title: `The 3 Best Ways to Pack Clothes for a Move`,
    date: "February 20, 2018",
    category: "Packing Tips",
    excerpt: `Packing clothes for a move can be more difficult than it may at first seem, and is often overlooked. However, we've got a few quick and easy tips that will help`,
    image: BRAND_IMAGES.crewCustomerCommercial,
    readTime: "3 min read",
  },
  {
    slug: "5-ways-to-maximize-space-in-your-small-home",
    title: `5 Ways to Maximize Space in Your Small Home`,
    date: "September 26, 2017",
    category: "Moving Tips",
    excerpt: `Living in a small house requires using all the space available. Here are a few tips for maximizing the space you have available.`,
    image: BRAND_IMAGES.crewFrontDoorExit,
    readTime: "3 min read",
  },
  {
    slug: "why-climate-controlled-storage-is-a-winning-choice",
    title: `Why Climate Controlled Storage is a Winning Choice`,
    date: "October 5, 2017",
    category: "Storage",
    excerpt: `Whether you're moving or just need extra space to store your belongings, climate controlled storage spaces are a great way to keep your belongings safe.`,
    image: BRAND_IMAGES.storageWarehouse,
    readTime: "4 min read",
  },
  {
    slug: "your-belongings-need-climate-controlled-storage",
    title: `Your Belongings Need Climate Controlled Storage`,
    date: "February 6, 2018",
    category: "Storage",
    excerpt: `Are you looking to move some of your belongings to storage to open up some space in your home? Climate controlled storage can keep your valuable belongings safe`,
    image: BRAND_IMAGES.storageWarehouse,
    readTime: "3 min read",
  },
  {
    slug: "best-things-to-do-in-everett-wa",
    title: `10 Exciting Things To Do In Everett In 2021`,
    date: "January 1, 2021",
    category: "Local Guides",
    excerpt: `Discover the best things to do in Everett, WA, including waterfront attractions, parks, museums, dining, and family-friendly activities.`,
    image: BRAND_IMAGES.truckSeattleSkyline,
    readTime: "4 min read",
  },
  {
    slug: "business-moving-hacks-tips-on-how-to-successfully-move-your-office-space",
    title: `Business Moving Hacks: Tips On How to Successfully Move Your Office Space`,
    date: "December 2, 2016",
    category: "Commercial Moving",
    excerpt: `Moving from one office to another can be a stressful process. Here's how you can move your business efficiently, safely, and affordably:`,
    image: BRAND_IMAGES.officeMoveAction,
    readTime: "4 min read",
  },
  {
    slug: "living-in-west-seattle",
    title: `7 Important Things To Know About Living In West Seattle, WA in 2022`,
    date: "January 6, 2021",
    category: "Local Guides",
    excerpt: `Thinking about living in West Seattle, WA? Discover lifestyle, housing, parks, local culture, commute options, and what makes this neighborhood unique.`,
    image: BRAND_IMAGES.truckSeattleSkyline,
    readTime: "5 min read",
  },
  {
    slug: "reasons-in-moving-to-bellevue-wa",
    title: `Reasons in Moving to Bellevue, WA`,
    date: "July 15, 2022",
    category: "Local Guides",
    excerpt: `Need to know what are the top reasons to move to Bellevue WA? Read this article from On The Go Moving and learn more.`,
    image: BRAND_IMAGES.truckBellevueSkyline,
    readTime: "3 min read",
  },
  {
    slug: "8-tips-for-organizing-small-spaces-and-creating-a-comfortable-home",
    title: `8 Tips for Organizing Small Spaces and Creating a Comfortable Home`,
    date: "August 2, 2018",
    category: "Moving Costs",
    excerpt: `Downsizing from a larger residence? Make the most of your space by using these 8 tips for moving into a smaller home and get practical ideas on organzing for sm`,
    image: BRAND_IMAGES.crewLoadingTruckRamp,
    readTime: "4 min read",
  },
  {
    slug: "how-to-announce-your-office-relocation-5-great-tips",
    title: `How to Announce Your Office Relocation 5 Great Tips`,
    date: "November 29, 2021",
    category: "Commercial Moving",
    excerpt: `Here are the great top five tips on how you can announce your office relocation to your employees. Be positive and upbeat. Check out now for more info.`,
    image: BRAND_IMAGES.officeMoveAction,
    readTime: "3 min read",
  },
  {
    slug: "best-time-to-rent-an-apartment-guide",
    title: `Best Time to Rent an Apartment An Essential Guide`,
    date: "September 1, 2022",
    category: "Specialty Moving",
    excerpt: `Need to know which is the best time to rent an apartment? Read this article from On The Go Moving and learn more.`,
    image: BRAND_IMAGES.crewLoadingTruckRamp,
    readTime: "3 min read",
  },
  {
    slug: "easing-transition-when-moving-senior",
    title: `Easing The Transition When Moving A Senior`,
    date: "June 26, 2018",
    category: "Senior Moving",
    excerpt: `How do you help a senior process the emotional stress of saying goodbye to a long-time home when it's time to move? An important part of moving a senior is maki`,
    image: BRAND_IMAGES.residentialService,
    readTime: "4 min read",
  },
  {
    slug: "how-to-keep-your-identity-safe-when-moving-to-bellevue",
    title: `How to Keep Your Identity Safe When Moving to Bellevue`,
    date: "July 13, 2016",
    category: "Specialty Moving",
    excerpt: `When it comes to a safe and secure move, your Bellevue moving company is here to help. Learn how you can avoid identity theft during your residential move. `,
    image: BRAND_IMAGES.truckBellevueSkyline,
    readTime: "3 min read",
  },
  {
    slug: "how-to-pack-for-a-move",
    title: `Best Way to Pack for Moving & How to Tips for Packing`,
    date: "March 26, 2023",
    category: "Packing Tips",
    excerpt: `Learn the best way to pack for moving, with a room-by-room list that includes supplies and a process filled with tips to make moving less stressful.`,
    image: BRAND_IMAGES.crewCarryingUpRamp,
    readTime: "3 min read",
  },
  {
    slug: "climate-controlled-storage-unit",
    title: `How Climate-Controlled Storage Can Help: Protecting Your Possessions Like a Pro`,
    date: "February 17, 2024",
    category: "Storage",
    excerpt: `Explore the reasons why climate control storage is a valuable solution, safeguarding your belongings. Contact On The Go Moving for climate-controlled storage so`,
    image: BRAND_IMAGES.warehouseCratesAlt,
    readTime: "4 min read",
  },
  {
    slug: "how-to-fold-for-packing",
    title: `How to Fold Clothes for Packing: Best Way to Fold for Suitcases`,
    date: "March 26, 2023",
    category: "Packing Tips",
    excerpt: `Figuring how to fold clothes for packing is important to avoid wrinkles. Find out how to fold, roll & arrange clothes to save space when you travel!`,
    image: BRAND_IMAGES.truckSeattleSkyline,
    readTime: "3 min read",
  },
  {
    slug: "helping-your-elderly-parents-or-grandparents-move",
    title: `Helping Your Elderly Parents or Grandparents Move`,
    date: "February 12, 2016",
    category: "Senior Moving",
    excerpt: `Moving elderly parents or grandparents can be a huge task. On The Go Moving and storage is experienced in helping senior citizens with a stress-free move.`,
    image: BRAND_IMAGES.residentialService,
    readTime: "3 min read",
  },
  {
    slug: "how-to-handle-last-minute-moves-successfully",
    title: `How to Handle Last-Minute Moves Successfully`,
    date: "August 22, 2024",
    category: "Moving Tips",
    excerpt: `Master your last-minute move with our emergency moving guide. Get last-minute moving tips and quick move solutions to navigate the hectic process smoothly.`,
    image: BRAND_IMAGES.crewCarryingUpRamp,
    readTime: "3 min read",
  },
  {
    slug: "comparing-self-storage-and-full-service-storage-options",
    title: `Comparing Self-Storage and Full-Service Storage Options`,
    date: "September 10, 2024",
    category: "Storage",
    excerpt: `Contact On The Go Moving and Storage to explore our diverse range of self-storage benefits and full-service storage advantages.`,
    image: BRAND_IMAGES.storageWarehouse,
    readTime: "3 min read",
  },
  {
    slug: "is-moving-stressful-for-seniors",
    title: `Is Moving Stressful for Seniors? Here’s How to Make It Easier`,
    date: "May 20, 2025",
    category: "Senior Moving",
    excerpt: `Moving is tough at any age, especially for seniors. Discover how senior moving assistance can make the process safer, easier, and less stressful.`,
    image: BRAND_IMAGES.residentialService,
    readTime: "4 min read",
  },
  {
    slug: "essential-tools-needed-for-a-smooth-move",
    title: `Essential Tools Needed for a Smooth Move`,
    date: "August 22, 2024",
    category: "Moving Tips",
    excerpt: `Discover essential packing supplies and tools like the heavy duty dolly needed for a smooth move. Ensure your belongings are secure and easy to transport.`,
    image: BRAND_IMAGES.crewStaircaseExit,
    readTime: "3 min read",
  },
  {
    slug: "benefits-of-using-professional-warehousing-services-during-your-move",
    title: `Benefits of Using Professional Warehousing Services During Your Move`,
    date: "September 3, 2024",
    category: "Moving Tips",
    excerpt: `Explore benefits of warehousing and storage solutions for moving with On The Go Moving and Storage. Secure, flexible options to simplify your transition.`,
    image: BRAND_IMAGES.crewOverheadEntrance,
    readTime: "3 min read",
  },
  {
    slug: "packing-before-your-move-everything-you-need-in-your-packing-survival-kit",
    title: `Packing Before Your Move: Everything You Need in Your Moving Day Survival Kit`,
    date: "April 29, 2015",
    category: "Packing Tips",
    excerpt: `Moving in Kirkland or the surrounding area? Here is a list of everything you need in your packing survival kit from the moving professionals`,
    image: BRAND_IMAGES.truckBellevueSkyline,
    readTime: "3 min read",
  },
  {
    slug: "how-to-move-efficiently-with-pets",
    title: `How to Move Efficiently with Pets`,
    date: "July 10, 2024",
    category: "Moving Tips",
    excerpt: `Master moving with pets with our expert pet-friendly moving tips. Learn crucial strategies for relocating with pets efficiently and stress-free.`,
    image: BRAND_IMAGES.threeCrewLoadingTruck,
    readTime: "3 min read",
  },
  {
    slug: "eco-friendly-moving-sustainable-practices-for-your-next-move",
    title: `Eco-Friendly Moving: Sustainable Practices for Your Next Move`,
    date: "December 21, 2024",
    category: "Moving Tips",
    excerpt: `Make your move sustainable with eco-friendly moving tips. Use environmentally friendly moving boxes and hire green movers for a low-waste relocation.`,
    image: BRAND_IMAGES.threeCrewRampLoading,
    readTime: "3 min read",
  },
  {
    slug: "moving-elderly-parents-out-of-their-home",
    title: `How To Relocate Your Elderly Parents Smoothly For Them`,
    date: "May 15, 2019",
    category: "Senior Moving",
    excerpt: `It can be hard when it comes time to move your elderly parents. To help the process go smoothly, we've compiled 7 tips for you and them.`,
    image: BRAND_IMAGES.residentialService,
    readTime: "3 min read",
  },
  {
    slug: "10-things-to-know-about-living-in-ballard",
    title: `10 Things to Know About Living in Ballard`,
    date: "December 26, 2017",
    category: "Local Guides",
    excerpt: `Life in Ballard has a ton to offer in terms of reasonable housing prices, a growing scene for food and nightlife, reputable school systems, safety, and a stable`,
    image: BRAND_IMAGES.truckSeattleSkyline,
    readTime: "4 min read",
  },
  {
    slug: "how-to-pack-shoes-for-moving-8-tips",
    title: `8 Tips On How To Pack Shoes For Moving`,
    date: "September 28, 2019",
    category: "Packing Tips",
    excerpt: `Remove the stress of packing your shoe collection, here are 8 simple tips to sort through and pack your shoe for moving. Don't forget to leave a pair out for mo`,
    image: BRAND_IMAGES.truckProfessionalLot,
    readTime: "4 min read",
  },
  {
    slug: "renting-a-house-for-the-first-time",
    title: `5 Tips For Renting A House For The First Time`,
    date: "July 23, 2019",
    category: "Moving Tips",
    excerpt: `Before you sign the lease on your first rental, there are a couple of things you should know. Read more information in our blog post.`,
    image: BRAND_IMAGES.crewHoodieAtTruck,
    readTime: "5 min read",
  },
  {
    slug: "12-seattle-moving-tasks-that-are-easily-forgotten",
    title: `12 Things To Do Before Moving (To Do List)`,
    date: "September 4, 2015",
    category: "Local Guides",
    excerpt: `Start planning things to do for moving with our checklist. Use our reminders and tips to prepare for your move from months before!`,
    image: BRAND_IMAGES.crewLoadingTruckRamp,
    readTime: "4 min read",
  },
  {
    slug: "sammamish-movers-guide",
    title: `Sammamish Mover’s Guide: How To Pay For A Move?`,
    date: "March 26, 2023",
    category: "Moving Tips",
    excerpt: `Want to know the Movers Guide in Sammamish and how to pay for a move once you the budget? Give On The Go Moving a call today to learn more.`,
    image: BRAND_IMAGES.crewLoadingTruckRamp,
    readTime: "3 min read",
  },
  {
    slug: "the-role-of-professional-movers-in-reducing-moving-stress",
    title: `The Role of Professional Movers in Reducing Moving Stress`,
    date: "July 5, 2024",
    category: "Moving Tips",
    excerpt: `By handling delicate items with a heavy duty hand truck and packing fragile box materials securely, professional movers help reduce moving stress.`,
    image: BRAND_IMAGES.threeCrewLoadingTruck,
    readTime: "3 min read",
  },
  {
    slug: "choosing-right-local-movers",
    title: `Why Choosing the Right Local Movers Makes All the Difference`,
    date: "April 16, 2025",
    category: "Moving Tips",
    excerpt: `Streamline your local move with On the Go Moving. Discover why choosing the right local movers is crucial for a stress-free experience. Get a free quote today!`,
    image: BRAND_IMAGES.crewCarryingUpRamp,
    readTime: "3 min read",
  },
  {
    slug: "how-to-choose-the-right-moving-company",
    title: `How to Choose the Right Moving Company`,
    date: "July 26, 2024",
    category: "Moving Tips",
    excerpt: `Discover essential best moving company tips and learn how to choose a moving company with confidence. Get expert advice on how to find reliable movers`,
    image: BRAND_IMAGES.crewStaircase1,
    readTime: "3 min read",
  },
  {
    slug: "living-on-mercer-island",
    title: `Living On Mercer Island Washington`,
    date: "January 22, 2021",
    category: "Local Guides",
    excerpt: `Want to know what living on Mercer Island is like? Lucky for you, residents that live in Mercer Island Washington have great things to say about their community`,
    image: BRAND_IMAGES.truckBellevueSkyline,
    readTime: "3 min read",
  },
  {
    slug: "living-in-west-bellevue-washington",
    title: `Living In West Bellevue Washington`,
    date: "April 16, 2021",
    category: "Local Guides",
    excerpt: `Learn more about the West Bellevue, Washington cost of living, the population of the city, as well as the best things to do in West Bellevue WA. Visit On the go`,
    image: BRAND_IMAGES.truckBellevueSkyline,
    readTime: "4 min read",
  },
  {
    slug: "living-in-everett-wa-you-need-to-know",
    title: `Living in Everett WA: Everything You Need to Know`,
    date: "September 1, 2022",
    category: "Local Guides",
    excerpt: `Are there any advantages to living in Everett, WA? Read this article on On The Go Moving & Storage to find out all the things to know about living here.`,
    image: BRAND_IMAGES.truckBrickBuilding,
    readTime: "3 min read",
  },
  {
    slug: "living-in-bothell-wa",
    title: `Living in Bothell WA`,
    date: "April 13, 2021",
    category: "Local Guides",
    excerpt: `Learn more about the Bothell Washington cost of living, the population of the city, as well as the best things to do in Bothell WA. Visit On the go moving to fi`,
    image: BRAND_IMAGES.truckResidentialStreet,
    readTime: "3 min read",
  },
  {
    slug: "green-moving-eco-friendly-10-tips",
    title: `Green Moving: 10 Tips How To Make Your Next Move Eco-Friendly for Earth Day 2021`,
    date: "January 7, 2021",
    category: "Moving Costs",
    excerpt: `Learn 10 actionable eco-friendly moving tips to reduce waste and carbon footprint during your next relocation.`,
    image: BRAND_IMAGES.truckKirklandHouse,
    readTime: "4 min read",
  },
  {
    slug: "living-in-woodinville-wa",
    title: `10 Things to Know About Living in Woodinville`,
    date: "March 3, 2021",
    category: "Local Guides",
    excerpt: `Woodinville is a delightful community that lies to the Northeast of Seattle. Let’s take a look at 10 things to know about living in Woodinville.`,
    image: BRAND_IMAGES.truckKirklandHouse,
    readTime: "4 min read",
  },
  {
    slug: "things-to-do-in-lynnwood-wa",
    title: `Things to Do in Lynnwood WA`,
    date: "September 2, 2021",
    category: "Local Guides",
    excerpt: `No matter whether you're planning a visit or to stay, you can count on a variety of fun things to do in Lynnwood, Washington. Read more!`,
    image: BRAND_IMAGES.truckBrickBuilding,
    readTime: "4 min read",
  },
  {
    slug: "living-in-renton-wa",
    title: `15 Things to Know About Living in Renton`,
    date: "August 4, 2020",
    category: "Local Guides",
    excerpt: `Thinking about living in Renton, Washington? Here are 15 things you will need to know before you make the big move to the southeast shore of Lake Washington`,
    image: BRAND_IMAGES.truckResidentialBuilding,
    readTime: "3 min read",
  },
  {
    slug: "what-to-know-about-living-in-kirkland",
    title: `What To Know About Living in Kirkland`,
    date: "August 8, 2017",
    category: "Local Guides",
    excerpt: `Kirkland, Washington, is becoming a popular city with a fast growing population. If you’re considering moving to Kirkland, read on to learn more about the city `,
    image: BRAND_IMAGES.truckKirklandHouse,
    readTime: "3 min read",
  },
  {
    slug: "living-in-kirkland-little-known-facts",
    title: `Living in Kirkland: Little Known Facts`,
    date: "November 7, 2018",
    category: "Local Guides",
    excerpt: `Looking to learn more about the City of Kirkland, Washington? We've assembled some little known facts about Kirkland that will give you a better understanding o`,
    image: BRAND_IMAGES.truckKirklandHouse,
    readTime: "3 min read",
  },
  {
    slug: "things-to-do-in-edmonds-wa",
    title: `Things to Do in Edmonds WA`,
    date: "September 2, 2021",
    category: "Local Guides",
    excerpt: `From outdoor activities to community-wide events, you can find many fun things to do in Edmonds, WA. They have the best restaurants too! Read more!`,
    image: BRAND_IMAGES.truckBrickBuilding,
    readTime: "4 min read",
  },
  {
    slug: "reasons-in-moving-to-ballard",
    title: `Reasons to Move to Ballard, WA`,
    date: "August 2, 2022",
    category: "Moving Tips",
    excerpt: `Need to know what are the top reasons to move to Ballard, WA? Read this article from On The Go Moving and learn more.`,
    image: BRAND_IMAGES.crewEntryway1,
    readTime: "3 min read",
  },
  {
    slug: "things-to-do-on-mercer-island",
    title: `Things to do on Mercer Island`,
    date: "June 2, 2021",
    category: "Local Guides",
    excerpt: `Don’t forget to share all of your local tips in the comments below and tell us what your favorite thing to do on Mercer Island is!Need help planning a move to M`,
    image: BRAND_IMAGES.truckBellevueSkyline,
    readTime: "3 min read",
  },
  {
    slug: "things-to-do-in-sammamish",
    title: `Things To Do In Sammamish`,
    date: "February 7, 2021",
    category: "Local Guides",
    excerpt: `Sammamish is full of all kind of events and activities to explore. Learn more about the area and the things to do in Sammamish!`,
    image: BRAND_IMAGES.truckResidentialBuilding,
    readTime: "3 min read",
  },
  {
    slug: "things-to-do-in-kirkland-wa",
    title: `Things to Do in Kirkland, WA`,
    date: "October 1, 2020",
    category: "Local Guides",
    excerpt: `Looking for things to do in Kirkland, WA? Explore waterfront parks, dining, shopping, outdoor activities, and local attractions for all ages.`,
    image: BRAND_IMAGES.truckKirklandHouse,
    readTime: "4 min read",
  },
  {
    slug: "things-to-do-in-woodinville",
    title: `Things to Do in Woodinville`,
    date: "March 3, 2021",
    category: "Local Guides",
    excerpt: `If you are planning to move or visit to Woodinville WA soon, then find out the things to do in while there? When moving across the country to Woodinville or fro`,
    image: BRAND_IMAGES.truckKirklandHouse,
    readTime: "5 min read",
  },
  {
    slug: "fun-things-to-do-in-bothell-wa",
    title: `10 Fun Things To Do In Bothell WA in 2021 | Plus Free Things To Do With Kids`,
    date: "January 6, 2021",
    category: "Local Guides",
    excerpt: `Explore the best things to do in Bothell, WA — from outdoor parks and family activities to local dining and entertainment. Discover top attractions and insider `,
    image: BRAND_IMAGES.truckResidentialStreet,
    readTime: "4 min read",
  },
  {
    slug: "things-to-do-in-bellevue",
    title: `15 Best Things To Do In Bellevue For Fun`,
    date: "July 20, 2020",
    category: "Local Guides",
    excerpt: `Bellevue is known for its beautiful sites and downtown skyline of gleaming high-rises. Find things to do in Bellevue WA at night or fun activities with kids. Do`,
    image: BRAND_IMAGES.truckBellevueSkyline,
    readTime: "4 min read",
  },
  {
    slug: "how-to-prepare-for-movers",
    title: `How to Prepare for Movers to Arrive?`,
    date: "August 23, 2023",
    category: "Moving Tips",
    excerpt: `After hiring a moving company for your upcoming move, you must know how to prepare for movers. To prepare for your movers before they arrive on a moving day.`,
    image: BRAND_IMAGES.truckProfessionalLot,
    readTime: "3 min read",
  },
  {
    slug: "how-to-protect-fragile-items-during-a-move",
    title: `How to Protect Fragile Items During a Move`,
    date: "December 20, 2024",
    category: "Moving Tips",
    excerpt: `Learn how to pack fragile items for moving safely. Get expert advice on protecting glass during a move and preventing damage with smart packing techniques.`,
    image: BRAND_IMAGES.crewEntryway2,
    readTime: "3 min read",
  },
  {
    slug: "things-to-do-in-issaquah",
    title: `15 Top Things To Do In Issaquah`,
    date: "June 8, 2020",
    category: "Local Guides",
    excerpt: `The Pacific Northwest is a beautiful and interesting place to live, and Issaquah is no exception. Here are 15 places to check out after your Issaquah move.`,
    image: BRAND_IMAGES.truckResidentialStreet,
    readTime: "5 min read",
  },
  {
    slug: "living-in-kirkland-wa",
    title: `10 Things To Know About Living In Kirkland, WA`,
    date: "January 13, 2020",
    category: "Local Guides",
    excerpt: `Considering a move to Kirkland, WA? Here are 10 important things you should know about living in Kirkland before taking the big step.`,
    image: BRAND_IMAGES.truckKirklandHouse,
    readTime: "5 min read",
  },
  {
    slug: "how-to-move-large-furniture-safely-and-efficiently",
    title: `How to Move Large Furniture Safely and Efficiently`,
    date: "December 20, 2024",
    category: "Specialty Moving",
    excerpt: `Learn furniture moving techniques to handle bulky items safely. Discover safe ways to move heavy furniture and tips for moving it upstairs efficiently`,
    image: BRAND_IMAGES.crewEntryway3,
    readTime: "3 min read",
  },
  {
    slug: "successful-yard-sale",
    title: `How to Have a Successful Yard Sale`,
    date: "July 11, 2017",
    category: "Moving Tips",
    excerpt: `Having a yard sale is a great way to declutter your house and get rid of the things that you just don’t want or need anymore. But, not all yard sales are create`,
    image: BRAND_IMAGES.crewDoorway1,
    readTime: "4 min read",
  },
  {
    slug: "stress-free-long-distance-movers",
    title: `How to Choose Stress-Free Long-Distance Movers for a Smooth Relocation`,
    date: "May 28, 2025",
    category: "Moving Tips",
    excerpt: `Discover how to make long-distance moving less stressful with reliable, professional movers. On The Go Moving offers stress-free moving services`,
    image: BRAND_IMAGES.crewEntryway1,
    readTime: "4 min read",
  },
  {
    slug: "first-time-moving-tips",
    title: `First Time Moving Tips`,
    date: "February 18, 2016",
    category: "Moving Costs",
    excerpt: `Experienced Bellevue Movers, On the Go Moving and Storage shares first time moving tips to ensure a stress-free move.`,
    image: BRAND_IMAGES.crewEntryway3,
    readTime: "3 min read",
  },
  {
    slug: "best-restaurants-in-seattle",
    title: `Best Seattle Seafood & International Restaurants to Visit in 2022`,
    date: "November 18, 2015",
    category: "Local Guides",
    excerpt: `On The Go Moving shares the names of several wonderful Seattle restaurants so that newcomers can enjoy the beauty and diversity of the city.`,
    image: BRAND_IMAGES.truckSeattleSkyline,
    readTime: "4 min read",
  },
  {
    slug: "how-can-you-prepare-your-items-for-long-term-storage",
    title: `How Can You Prepare Your Items for Long-Term Storage?`,
    date: "September 5, 2024",
    category: "Storage",
    excerpt: `Explore long-term storage tips and preparing items for storage with our guide. Learn how to protect your stuff with the right long-term storage solutions.`,
    image: BRAND_IMAGES.storageWarehouse,
    readTime: "3 min read",
  },
  {
    slug: "attractions-in-seattle",
    title: `Seattle Attractions - Places To Visit in the Emerald City`,
    date: "July 4, 2023",
    category: "Local Guides",
    excerpt: `Find Seattle attractions to know the best places and the best things to do in Seattle. Know more about the top-rated & must-see attractions. Visit us today!`,
    image: BRAND_IMAGES.truckSeattleSkyline,
    readTime: "4 min read",
  },
  {
    slug: "shopping-in-seattle",
    title: `Seattle Shopping: The Best Places for New Residents to Visit`,
    date: "March 26, 2023",
    category: "Local Guides",
    excerpt: `Find the best options while shopping in Seattle. We can show you the best options in the downtown shopping district!`,
    image: BRAND_IMAGES.truckSeattleSkyline,
    readTime: "4 min read",
  },
  {
    slug: "things-to-do-in-seattle-in-summer",
    title: `15 Fun Things To Do In Seattle In Summer`,
    date: "July 7, 2020",
    category: "Local Guides",
    excerpt: `Summers in Seattle, the seaport city of the West Coast, are unmatched. Here are 15 fun things to do in the city this summer to truly experience Seattle.`,
    image: BRAND_IMAGES.truckSeattleSkyline,
    readTime: "3 min read",
  },
  {
    slug: "best-places-to-live-in-seattle-neighborhoods-near-the-area",
    title: `Best Places To Live In Seattle: Neighborhoods Near The Area`,
    date: "May 16, 2023",
    category: "Local Guides",
    excerpt: `Learn about the best places to live in Seattle, we will guide you through the best neighborhoods in the area. Don’t miss our gems for buyers!`,
    image: BRAND_IMAGES.truckSeattleSkyline,
    readTime: "3 min read",
  },
  {
    slug: "5-moving-mistakes-seattle-families",
    title: `Top 5 Moving Mistakes Seattle Families Make`,
    date: "August 24, 2015",
    category: "Local Guides",
    excerpt: `It can be easy to overlook some tasks when preparing for a big move. On The Go Moving warns against making these top five moving mistakes.`,
    image: BRAND_IMAGES.crewCarryingUpRamp,
    readTime: "3 min read",
  },
  {
    slug: "living-in-fremont-seattle",
    title: `Living in Fremont Seattle`,
    date: "August 31, 2020",
    category: "Local Guides",
    excerpt: `Fremont is situated along the Fremont Cut of the Lake Washington Ship Canal to the north of Queen Anne, Seattle. Fremont has something for everyone, no matter i`,
    image: BRAND_IMAGES.truckSeattleSkyline,
    readTime: "5 min read",
  },
  {
    slug: "bellevue-or-seattle-where-to-live",
    title: `Bellevue or Seattle Where To Live`,
    date: "July 5, 2021",
    category: "Local Guides",
    excerpt: `Learn more about the pros and cons of Bellevue vs Seattle for living, or get in touch with On The Go Moving to speak with a reliable moving service about your r`,
    image: BRAND_IMAGES.truckBellevueSkyline,
    readTime: "3 min read",
  },
  {
    slug: "living-in-beacon-hill-seattle",
    title: `Living in Beacon Hill, Seattle: A Neighborhood Overview`,
    date: "September 14, 2020",
    category: "Local Guides",
    excerpt: `Considering living in Beacon Hill, Seattle? Learn about housing, lifestyle, parks, transit, and what makes this neighborhood a great place to live.`,
    image: BRAND_IMAGES.truckSeattleSkyline,
    readTime: "5 min read",
  },
  {
    slug: "best-things-to-do-in-fremont-seattle-wa",
    title: `7 Fun Things To Do In Fremont Seattle`,
    date: "February 28, 2020",
    category: "Local Guides",
    excerpt: `Fremont Seattle is an exciting place to live. Explore the top things to do in Fremont for a fun weekend plan out in the city.`,
    image: BRAND_IMAGES.truckSeattleSkyline,
    readTime: "4 min read",
  },
  {
    slug: "seattle-packing-tips-plastic-bins-or-cardboard-boxes",
    title: `Seattle Packing Tips: Plastic Bins or Cardboard Boxes?`,
    date: "September 2, 2016",
    category: "Packing Tips",
    excerpt: `Are you packing for a move? Here are the pros and cons between cardboard boxes and plastic bins. Read on for helpful Seattle packing tips:`,
    image: BRAND_IMAGES.truckBrickBuilding,
    readTime: "3 min read",
  },
  {
    slug: "living-in-capitol-hill-seattle",
    title: `12 Interesting Things You Should Know About Living In Capitol Hill, Seattle`,
    date: "September 27, 2019",
    category: "Local Guides",
    excerpt: `Are you considering a move to the Capitol Hill neighborhood of Seattle, Washington? If so, then here are 12 things you should know about your new home town.`,
    image: BRAND_IMAGES.truckSeattleSkyline,
    readTime: "4 min read",
  },
  {
    slug: "9-smart-seattle-packing-tips",
    title: `9 Smart Seattle Packing Tips`,
    date: "July 25, 2016",
    category: "Specialty Moving",
    excerpt: `If you're planning a move in the Seattle area, On The Go Moving and Storage is here to help. Here are 9 Seattle packing tips to streamline the whole process.`,
    image: BRAND_IMAGES.truckResidentialBuilding,
    readTime: "4 min read",
  },
  {
    slug: "tips-to-choosing-the-best-student-moving-services-in-seattle",
    title: `Tips for Choosing the Best Dorm Room Moving Services in Seattle`,
    date: "September 18, 2018",
    category: "Moving Costs",
    excerpt: `Moving into a new place before school starts? Learn how to find a moving company that will make your transition into your new lodging easy and inexpensive.`,
    image: BRAND_IMAGES.truckSeattleSkyline,
    readTime: "3 min read",
  },
  {
    slug: "moving-to-seattle-after-graduation",
    title: `What Is Living in Seattle As Young Adult Like?`,
    date: "July 8, 2016",
    category: "Local Guides",
    excerpt: `Seattle has a triving young adult culture and that's a main reason so many millennials are deciding to live and work in Seattle. Is it right for you?`,
    image: BRAND_IMAGES.truckSeattleSkyline,
    readTime: "3 min read",
  },
  {
    slug: "living-in-belltown-seattle-wa",
    title: `Living in Belltown, Seattle, WA: A Neighborhood Overview`,
    date: "October 16, 2020",
    category: "Local Guides",
    excerpt: `Thinking about living in Belltown, Seattle, WA? Learn about housing, lifestyle, walkability, nightlife, and what daily life is like in Belltown.`,
    image: BRAND_IMAGES.truckSeattleSkyline,
    readTime: "4 min read",
  },
  {
    slug: "living-in-queen-anne-seattle",
    title: `Living in Queen Anne Seattle`,
    date: "October 23, 2020",
    category: "Local Guides",
    excerpt: `Thinking about living in Queen Anne, Seattle? Learn about housing, views, walkability, parks, and what daily life is like in this iconic neighborhood.`,
    image: BRAND_IMAGES.truckSeattleSkyline,
    readTime: "4 min read",
  },
  {
    slug: "parks-near-downtown-seattle",
    title: `Parks Near Downtown Seattle, WA`,
    date: "June 3, 2022",
    category: "Local Guides",
    excerpt: `Welcome to the official On The Go Moving site. Go through the blog post to see the best Parks Near Downtown Seattle, WA that makes Seattle such an exciting urba`,
    image: BRAND_IMAGES.truckSeattleSkyline,
    readTime: "3 min read",
  },
  {
    slug: "moving-to-seattle",
    title: `30 Things You Should Know About Living In Seattle Before Moving There In 2022 | The Emerald City Relocation Guide`,
    date: "March 15, 2021",
    category: "Local Guides",
    excerpt: `Planning on moving to Seattle? Learn about the cost of living, best neighborhoods, weather, and expert tips to make your Seattle move stress-free.`,
    image: BRAND_IMAGES.truckSeattleSkyline,
    readTime: "5 min read",
  },
  {
    slug: "restaurant-in-redmond",
    title: `Best Restaurants in Redmond WA`,
    date: "January 7, 2022",
    category: "Local Guides",
    excerpt: `Looking for the best restaurant around Redmond that offers healthy and delicious foods? This article is what you're looking for! Read more and call us today!`,
    image: BRAND_IMAGES.truckResidentialStreet,
    readTime: "3 min read",
  },
  {
    slug: "9-tips-you-will-want-to-know-for-your-next-redmond-move",
    title: `9 Tips You Will Want to Know for Your Next Redmond Move`,
    date: "April 15, 2016",
    category: "Moving Costs",
    excerpt: `On the Go Moving and Storage offers experienced packing, moving, and storage services in the Redmond area. Contact us to learn how we help with your next move.`,
    image: BRAND_IMAGES.truckResidentialStreet,
    readTime: "3 min read",
  },
  {
    slug: "5-best-reasons-to-move-to-redmond",
    title: `5 Best Reasons to Move to Redmond`,
    date: "May 18, 2016",
    category: "Local Guides",
    excerpt: `Many people are moving to the Pacific Northwest because of its beauty and business opportunities. For those that want a little less congestion while still havin`,
    image: BRAND_IMAGES.truckResidentialStreet,
    readTime: "3 min read",
  },
  {
    slug: "best-things-to-do-in-redmond",
    title: `22 Top Things To Do in Redmond`,
    date: "June 4, 2021",
    category: "Local Guides",
    excerpt: `Explore the best things to do in Redmond, WA — parks, trails, tech attractions, family fun, shopping, and local experiences for residents and visitors.`,
    image: BRAND_IMAGES.truckResidentialStreet,
    readTime: "4 min read",
  },
  {
    slug: "10-things-you-should-know-about-living-in-redmond-washington",
    title: `10 Things You Should Know About Living in Redmond, Washington`,
    date: "March 17, 2016",
    category: "Local Guides",
    excerpt: `If you're thinking about moving to Redmond, On The Go Moving has a list of 10 things you should know. `,
    image: BRAND_IMAGES.truckResidentialStreet,
    readTime: "5 min read",
  },
  {
    slug: "things-to-do-in-shoreline-wa",
    title: `Things to Do in Shoreline, WA: Parks, Attractions & Activities`,
    date: "November 21, 2020",
    category: "Local Guides",
    excerpt: `Discover the best things to do in Shoreline, WA, including parks, outdoor activities, dining, and local attractions for all ages.`,
    image: BRAND_IMAGES.truckResidentialStreet,
    readTime: "4 min read",
  },
  {
    slug: "parks-in-bellevue",
    title: `Parks In Bellevue WA | Water Recreation, Park Near Bellevue Square`,
    date: "July 11, 2020",
    category: "Local Guides",
    excerpt: `Bellevue is known for having some beautiful parks. Form lushish green to refreshing water, check out the top 7 parks to visit in the Bellevue area!`,
    image: BRAND_IMAGES.truckBellevueSkyline,
    readTime: "4 min read",
  },
  {
    slug: "living-in-downtown-seattle",
    title: `What Is It Like Living in Downtown Seattle? | Cost of Living, Parking, Traffic,`,
    date: "May 12, 2020",
    category: "Local Guides",
    excerpt: `Downtown Seattle can be an exciting place to live! Before you take the leap to live in the center of the Emerald City, here are four things you should know.`,
    image: BRAND_IMAGES.truckSeattleSkyline,
    readTime: "4 min read",
  },
  {
    slug: "parks-in-lynnwood",
    title: `Best Parks in Lynnwood`,
    date: "November 23, 2021",
    category: "Local Guides",
    excerpt: `Discover the best trails, hiking and other outdoor activities in the best parks in lynnwood. On the Go moving has different locations to explore.`,
    image: BRAND_IMAGES.truckBrickBuilding,
    readTime: "3 min read",
  },
  {
    slug: "parks-in-seattle",
    title: `Parks in Seattle, WA`,
    date: "January 7, 2022",
    category: "Local Guides",
    excerpt: `Thinking about a country to move to where there are plenty of relaxing parks and views? Check out this article and you will find about the best parks in Seattle`,
    image: BRAND_IMAGES.truckSeattleSkyline,
    readTime: "3 min read",
  },
  {
    slug: "seattle-restaurant-fremont",
    title: `Best Restaurants in Fremont Seattle, WA`,
    date: "January 11, 2022",
    category: "Local Guides",
    excerpt: `Are you looking for the best restaurants in Fremont, Seattle that will satisfy your cravings? This article is for you. Read more to find out!`,
    image: BRAND_IMAGES.truckSeattleSkyline,
    readTime: "3 min read",
  },
  {
    slug: "lake-sammamish-parks",
    title: `Lake Sammamish Parks`,
    date: "August 3, 2021",
    category: "Local Guides",
    excerpt: `Are you looking for the ideal park in Lake Sammamish? Visit On The Go Moving, to learn about the best parks & things to do in and around Sammamish, Washington.`,
    image: BRAND_IMAGES.truckResidentialBuilding,
    readTime: "3 min read",
  },
  {
    slug: "kirkland-waterfront",
    title: `Kirkland Waterfront`,
    date: "August 9, 2021",
    category: "Local Guides",
    excerpt: `Learn more about the Kirkland's iconic waterfront, find the best parks, trails, and waterfront restaurants in the area. Visit On The Go Moving for more details.`,
    image: BRAND_IMAGES.truckKirklandHouse,
    readTime: "3 min read",
  },
  {
    slug: "parks-in-redmond-wa",
    title: `Redmond Parks`,
    date: "June 7, 2021",
    category: "Local Guides",
    excerpt: `Discover the best parks in Redmond WA, from trails to family-friendly spaces, plus local tips for living and moving in Redmond.`,
    image: BRAND_IMAGES.truckResidentialStreet,
    readTime: "5 min read",
  },
  {
    slug: "what-is-seattle-known-for-food-sights",
    title: `What Seattle Is Known For — Best Food & Iconic Sights`,
    date: "April 29, 2021",
    category: "Local Guides",
    excerpt: `Explore what Seattle is known for — iconic food and best sights from Pike Place Market to Space Needle, plus local travel tips and moving insights.`,
    image: BRAND_IMAGES.truckSeattleSkyline,
    readTime: "4 min read",
  },
  {
    slug: "mercer-island-restaurants",
    title: `The Best Restaurants, Parks, & Recreation Centers in Mercer Island`,
    date: "November 23, 2021",
    category: "Local Guides",
    excerpt: `Looking for best restaurants, parks and recreation center in Mercer Island?On the Go moving has different locations to explore. Learn more.`,
    image: BRAND_IMAGES.truckBellevueSkyline,
    readTime: "3 min read",
  },
  {
    slug: "how-to-move-a-piano",
    title: `Do It Yourself: Best Way To Move A Piano`,
    date: "November 20, 2019",
    category: "Specialty Moving",
    excerpt: `Moving your piano can be daunting task. Here are our expert tips to make sure your piano and your back both remain intact throughout the process.`,
    image: BRAND_IMAGES.crewRamp,
    readTime: "4 min read",
  },
  {
    slug: "best-days-of-week-to-move-seattle",
    title: `The Best Days of the Week to Move in Seattle`,
    date: "August 10, 2015",
    category: "Local Guides",
    excerpt: `While it may not seem significant, it is important to select a day of the week that will leave you with the necessary time and resources to complete your move q`,
    image: BRAND_IMAGES.threeCrewLoadingTruck,
    readTime: "3 min read",
  },
  {
    slug: "office-moves-checklist",
    title: `Office Moving Checklist: List For Moving Offices`,
    date: "July 4, 2023",
    category: "Commercial Moving",
    excerpt: `Businesses planning to relocate can take advantage of our office moving checklist. Make a smooth transition with your workforce to a new space. Start planning s`,
    image: BRAND_IMAGES.officeMoveAction,
    readTime: "4 min read",
  },
  {
    slug: "when-is-the-best-time-to-move-into-an-apartment",
    title: `When Is the Best Time to Move Into an Apartment?`,
    date: "November 2, 2022",
    category: "Specialty Moving",
    excerpt: `Need to know which is the best time to move into an apartment? Read this article from On The Go Moving and learn more.`,
    image: BRAND_IMAGES.crewDoorway2,
    readTime: "4 min read",
  },
  {
    slug: "temporary-storage-for-your-small-business",
    title: `Why Use Temporary Storage for Your Small Business`,
    date: "January 15, 2016",
    category: "Commercial Moving",
    excerpt: `On The Go Moving and Storage shares how temporary storage can help save you time and money during your next small business move.`,
    image: BRAND_IMAGES.warehouseInterior,
    readTime: "3 min read",
  },
  {
    slug: "9-moving-lessons-dont-have-to-learn-hard-way",
    title: `9 Moving Lessons You Don’t Have to Learn the Hard Way`,
    date: "November 5, 2015",
    category: "Moving Tips",
    excerpt: `On The Go Moving and Storage shares 9 simple tricks that can transform your moving experience from hectic and stressful to easy and simple.`,
    image: BRAND_IMAGES.crewDoorway3,
    readTime: "5 min read",
  },
  {
    slug: "office-moving-tips",
    title: `How To Keep Your Office Moving Organized And Easy`,
    date: "August 1, 2017",
    category: "Commercial Moving",
    excerpt: `Moving an entire office can at first seem overwhelming. To combat potential chaos, we've created a month by month office moving plan to keep you organized.`,
    image: BRAND_IMAGES.crewWrappingOffice,
    readTime: "4 min read",
  },
  {
    slug: "best-office-organization-systems",
    title: `Office Organization Systems | How To Organize An Office Space | Tips For Arranging Your Work`,
    date: "March 23, 2020",
    category: "Commercial Moving",
    excerpt: `Struggling to keep your office organized? Follow our eight easy steps to arrange your space into a system that works for you and your team.`,
    image: BRAND_IMAGES.officeMoveAction,
    readTime: "4 min read",
  },
  {
    slug: "things-to-do-in-downtown-seattle-washington",
    title: `Things to Do in Downtown Seattle WA`,
    date: "February 22, 2022",
    category: "Local Guides",
    excerpt: `Wondering what to do in Seattle, WA? Check out these exciting and fun things to do in Downtown Seattle, WA for an epic travel adventure.`,
    image: BRAND_IMAGES.truckSeattleSkyline,
    readTime: "4 min read",
  },
  {
    slug: "7-tips-relocating-small-business-office",
    title: `7 Tips for Relocating Your Small Business Office`,
    date: "September 16, 2015",
    category: "Commercial Moving",
    excerpt: `On The Go Moving offers business owners seven simple tips to help make the task of relocating their small business offices fast and simple.`,
    image: BRAND_IMAGES.officeMoveAction,
    readTime: "4 min read",
  },
  {
    slug: "residential-moving-services-guide",
    title: `A Complete Guide For Residential Moving Services`,
    date: "November 28, 2023",
    category: "Moving Tips",
    excerpt: `If you are looking for guidance on smoothing out your moving process. Well, you have come to the right place. This guide will help you navigate the moving proce`,
    image: BRAND_IMAGES.crewEntryway1,
    readTime: "4 min read",
  },
  {
    slug: "innovative-commercial-movers-seattle",
    title: `Innovative Commercial Movers in Seattle: Advanced Moving Systems for Your Business`,
    date: "April 15, 2025",
    category: "Commercial Moving",
    excerpt: `Looking for innovative commercial movers in Seattle? Discover cutting-edge moving systems and efficient commercial moving solutions for your business with On Th`,
    image: BRAND_IMAGES.officeMoveAction,
    readTime: "4 min read",
  },
  {
    slug: "office-relocation",
    title: `Tips For Making Your Office Relocation Easier`,
    date: "March 26, 2023",
    category: "Commercial Moving",
    excerpt: `Follow these tips to plan your office relocation the right way. Make sure your move to a new business location is smooth and stress free!`,
    image: BRAND_IMAGES.officeMoveAction,
    readTime: "4 min read",
  },
  {
    slug: "how-to-pack-clothes-for-moving",
    title: `How to Pack Clothes For Moving | Best Way To Move Clothes`,
    date: "November 29, 2019",
    category: "Packing Tips",
    excerpt: `Packing clothes for moving can seem like a daunting task, make it easy for yourself by exploring our best tips for how to pack your clothes efficiently and simp`,
    image: BRAND_IMAGES.truckResidentialStreet,
    readTime: "6 min read",
  },
  {
    slug: "living-in-bellevue-wa",
    title: `20 Things You Should Know Before Moving To Bellevue, WA`,
    date: "May 30, 2021",
    category: "Local Guides",
    excerpt: `When most people think of Bellevue, they tend to think of it as a suburb of Seattle. If you’ve been considering moving to Bellevue, you’re probably eager to lea`,
    image: BRAND_IMAGES.truckBellevueSkyline,
    readTime: "5 min read",
  },
  {
    slug: "moving-to-a-new-city-alone",
    title: `Moving To A New City Alone | What To Do & How To Face The Challenges Of Moving Out Of State`,
    date: "January 13, 2020",
    category: "Moving Tips",
    excerpt: `Moving to a new city alone can feel frightening and lonely. Sometimes you feel you just don't know what to do next or how to fit in. To help make this next exci`,
    image: BRAND_IMAGES.crewCarryingFurniture,
    readTime: "3 min read",
  },
  {
    slug: "7-helpful-tips-when-moving-with-pets",
    title: `7 Helpful Tips When Moving With Pets`,
    date: "January 30, 2018",
    category: "Moving Costs",
    excerpt: `Need help in moving with the pets? Consider this article by On The Go Moving and get best in class advice and help in making your moving process successful.`,
    image: BRAND_IMAGES.customerHandshake,
    readTime: "4 min read",
  },
  {
    slug: "4-common-moving-mistakes",
    title: `How To Avoid the 4 Most Common Moving Mistakes`,
    date: "December 9, 2015",
    category: "Moving Tips",
    excerpt: `Moving can stressful and it can be easy to forget things or let things slip through cracks, here are 4 common mistakes everyone makes and how to avoid them.`,
    image: BRAND_IMAGES.crewCarryingOut,
    readTime: "3 min read",
  },
  {
    slug: "most-trusted-movers-residential-seattle",
    title: `Most Trusted Movers Residential in Seattle`,
    date: "October 28, 2022",
    category: "Local Guides",
    excerpt: `Know about the most trusted Movers Residential Seattle, how to save money in moving, cheapest way to move. Give On The Go Moving a call now to learn more.`,
    image: BRAND_IMAGES.threeCrewLoadingTruck,
    readTime: "4 min read",
  },
  {
    slug: "things-to-do-in-seattle-in-winter",
    title: `Things To Do in Seattle in Winter`,
    date: "January 5, 2021",
    category: "Local Guides",
    excerpt: `If you're looking for things to do in Seattle during winter, then time to discover all Seattle has to offer. Seattle has no shortage of fun things to do during `,
    image: BRAND_IMAGES.truckSeattleSkyline,
    readTime: "5 min read",
  },
  {
    slug: "best-time-of-year-to-move",
    title: `When is the Best Time Of The Year To Move`,
    date: "March 16, 2022",
    category: "Moving Tips",
    excerpt: `Need to know which is the best time of the year to move? Read this article from On The Go Moving and learn more.`,
    image: BRAND_IMAGES.crewFrontDoorExit,
    readTime: "3 min read",
  },
  {
    slug: "affordable-expert-office-movers",
    title: `Finding Affordable Expert Office Movers`,
    date: "April 30, 2025",
    category: "Commercial Moving",
    excerpt: `Need reliable office movers that fit your budget? Discover how to find affordable expert office relocation solutions with On The Go Moving. Get a free quote tod`,
    image: BRAND_IMAGES.officeMoveAction,
    readTime: "4 min read",
  },
  {
    slug: "declutter-your-home-checklist-for-moving",
    title: `Declutter Your Home Checklist for Moving`,
    date: "July 15, 2022",
    category: "Moving Tips",
    excerpt: `Get a checklist for your declutter home moving and after that you don't forget anything. Contact us today!`,
    image: BRAND_IMAGES.crewRollingRug,
    readTime: "3 min read",
  },
  {
    slug: "apartment-moving-tips",
    title: `Apartment Moving Tips | How To Move Into An Apartment`,
    date: "May 21, 2020",
    category: "Specialty Moving",
    excerpt: `Moving into a new apartment can be tough, so our team offers some easy tips to make the moving process simple and efficient.`,
    image: BRAND_IMAGES.crewLoadingTruckRamp,
    readTime: "5 min read",
  },
];

export const BLOG_CATEGORIES = ["All", "Commercial Moving", "Local Guides", "Moving Costs", "Moving Tips", "Packing Tips", "Senior Moving", "Specialty Moving", "Storage"];
