// ON THE GO MOVING — Blog Index Posts (auto-generated)
// Generated: 2026-04-07
// ==========================================================================

import { BRAND_IMAGES } from "@/lib/brandImages";

export interface BlogIndexPost {
  slug: string;
  title: string;
  date: string;
  category: string;
  excerpt: string;
  image: string;
  readTime: string;
}

export const BLOG_POSTS: BlogIndexPost[] = [
  {
    slug: "moving-tips-how-to-pack-up-your-garage-for-moving",
    title: `Moving Tips: How to Pack Up Your Garage for Moving`,
    date: "December 16, 2016",
    category: "Packing Tips",
    excerpt: `When it comes to moving, packing up the garage can be quite the project. Here are a few helpful moving tips for making the process go swiftly and smoothly.`,
    image: BRAND_IMAGES.truckSeattleSkyline,
    readTime: "5 min read",
  },
  {
    slug: "how-to-pack-tv-for-moving",
    title: `How To Pack Your Flat Screen TV for Moving | 4 Expert Tips`,
    date: "November 15, 2019",
    category: "Packing Tips",
    excerpt: `Not sure how to safely pack your TV for moving? Explore four expert tips for quickly and securely transporting your TV to your new home.`,
    image: BRAND_IMAGES.truckBellevueSkyline,
    readTime: "3 min read",
  },
  {
    slug: "8-tips-move-bad-weather",
    title: `8 Tips to Help You Move in The Rain`,
    date: "October 8, 2018",
    category: "Moving Costs",
    excerpt: `Moving in bad weather is never easy. These 8 moving tips will help you cope successfully with moving house or apartment in bad weather.`,
    image: BRAND_IMAGES.truckProfessionalLot,
    readTime: "3 min read",
  },
  {
    slug: "changing-your-address-essential-checklist",
    title: `An Essential Checklist for Changing Your Address`,
    date: "September 30, 2016",
    category: "Moving Tips",
    excerpt: `Moving means changing your address. Here's a step by step guide on how to change your address and communicate with people who need your new address.`,
    image: BRAND_IMAGES.crewHoodieAtTruck,
    readTime: "4 min read",
  },
  {
    slug: "moving-tips-the-right-way-to-pack-a-bathroom",
    title: `Moving Tips: The Right Way to Pack a Bathroom`,
    date: "October 7, 2016",
    category: "Packing Tips",
    excerpt: `Getting ready for the big move? Here are some helpful moving tips on how to pack your bathroom efficiently and economically.`,
    image: BRAND_IMAGES.truckBrickBuilding,
    readTime: "3 min read",
  },
  {
    slug: "how-to-efficiently-pack-a-storage-container",
    title: `How to Efficiently Pack A Storage Container`,
    date: "August 17, 2018",
    category: "Packing Tips",
    excerpt: `Looking for ways to maximize the space in your storage container? Explore our four helpful tips to efficiently and securely pack your belongings for storage.`,
    image: BRAND_IMAGES.truckResidentialBuilding,
    readTime: "3 min read",
  },
  {
    slug: "how-to-pack-a-storage-unit",
    title: `How to Pack and Organize a Storage Unit | Best Tips for Ease of Access`,
    date: "March 27, 2020",
    category: "Packing Tips",
    excerpt: `If this is your first time packing a storage unit, our moving experts here at On The Go Moving have compiled a list of 6 helpful, organizational tips for you.`,
    image: BRAND_IMAGES.warehouseInterior,
    readTime: "5 min read",
  },
  {
    slug: "storage-unit-prices",
    title: `Storage Unit Prices`,
    date: "July 16, 2021",
    category: "Moving Costs",
    excerpt: `Learn more about storage unit prices and what solutions are available to you. Get in touch with On The Go Moving today, for more details.`,
    image: BRAND_IMAGES.teamMemberWarehouse,
    readTime: "4 min read",
  },
  {
    slug: "leave-behind-moving-5-ways-declutter-house",
    title: `What to Leave Behind When Moving: 5 Ways to Declutter Your House`,
    date: "June 26, 2017",
    category: "Moving Tips",
    excerpt: `Take the process of moving as an opportunity to rid yourself of the clutter that has collected over the years and start fresh. Whether it’s your first big move `,
    image: BRAND_IMAGES.crewFloorProtection1,
    readTime: "3 min read",
  },
  {
    slug: "packing-fragile-items",
    title: `Packing Fragile Items Prior to Moving`,
    date: "October 28, 2022",
    category: "Packing Tips",
    excerpt: `Learn about Packing Fragile Items prior to moving, from the cost and types of damages of the items. Give On The Go Moving a call today to learn more.`,
    image: BRAND_IMAGES.crewWrappingFurniture,
    readTime: "4 min read",
  },
  {
    slug: "best-tips-for-winter-moving",
    title: `Best Tips for Winter Moving`,
    date: "March 16, 2022",
    category: "Moving Costs",
    excerpt: `Are you planning for winter moving? Find out all of our best moving suggestions to make the process go more smoothly. Visit us now.`,
    image: BRAND_IMAGES.truckResidentialStreet,
    readTime: "3 min read",
  },
  {
    slug: "how-to-pack-a-car-for-moving",
    title: `Helpful Tips On How to Pack A Car for Moving`,
    date: "January 16, 2018",
    category: "Packing Tips",
    excerpt: `Explore helpful tips on how to pack a car for moving, including tricks and strategies for how you can safely and effectively pack your car for your move.`,
    image: BRAND_IMAGES.customerHandshake,
    readTime: "4 min read",
  },
  {
    slug: "benefits-of-climate-controlled-storage",
    title: `8 Reasons Climate Controlled Storage Units Are Best For Indoor Storage`,
    date: "March 30, 2017",
    category: "Storage",
    excerpt: `Climate-controlled storage provides many improvements over outdoor storage, and some items even require climate-controlled vaults over outdoor units. Below we’l`,
    image: BRAND_IMAGES.warehouseCratesAlt,
    readTime: "5 min read",
  },
  {
    slug: "tricks-to-unpack-your-home-in-2-days",
    title: `How To Unpack After Moving In 2 Days`,
    date: "October 21, 2016",
    category: "Packing Tips",
    excerpt: `How to unpack after a move can be crucial, if you don’t do it the right way it can turn in a daunting experience. Follow our tips to unpack quickly & smoothly!`,
    image: BRAND_IMAGES.crewDoorway2,
    readTime: "3 min read",
  },
  {
    slug: "moving-into-new-house",
    title: `11 Tips To Do First After Moving Into A New House`,
    date: "November 30, 2019",
    category: "Moving Tips",
    excerpt: `Congratuations on your new home! Now what? Explore the first 11 things to do after moving into your new house so you can feel comfortable in your new home as so`,
    image: BRAND_IMAGES.crewDoorway1,
    readTime: "5 min read",
  },
  {
    slug: "hiring-professional-movers-vs-moving-yourself",
    title: `What To Know About Hiring Professional Movers vs Moving Yourself`,
    date: "December 1, 2021",
    category: "Moving Tips",
    excerpt: `Have trouble between hiring a moving company or DIY for moving? Read now for more information about the pros and cons of hiring and DIY moving.`,
    image: BRAND_IMAGES.customerHandshake,
    readTime: "3 min read",
  },
  {
    slug: "housewarming-party-ideas-and-food",
    title: `Ideas For The Ultimate Housewarming Party | Planning Food, Themes, Games, & Drinks`,
    date: "September 27, 2019",
    category: "Specialty Moving",
    excerpt: `Planning a housewarming party doesn’t need to be stress-inducing at all. Rather it gives you a fun chance to whip out your creative skills and introduce people.`,
    image: BRAND_IMAGES.crewEntryway1,
    readTime: "5 min read",
  },
  {
    slug: "first-time-moving-heres-simple-checklist",
    title: `Checklist: First Time Moving Out | Tips For Packing Room By Room`,
    date: "August 22, 2017",
    category: "Moving Tips",
    excerpt: `Now that you’re ready to move out for the first time, the next step is to get organized and plan your move down to the smallest detail. To make things easier fo`,
    image: BRAND_IMAGES.crewEntryway3,
    readTime: "3 min read",
  },
  {
    slug: "how-to-pack-dishes",
    title: `How To Pack Dishes | Kitchenware, Pots and Pans, and Glasses`,
    date: "September 27, 2019",
    category: "Packing Tips",
    excerpt: `The last thing you want is breaking any of your dishes while moving, that's why we've compiled a 5 step process to packing your dishes safely and securely.`,
    image: BRAND_IMAGES.crewWrappingFurniture,
    readTime: "3 min read",
  },
  {
    slug: "how-to-find-the-best-temporary-storage-units-in-your-area",
    title: `How to Find the Best Temporary Storage Units in Your Area`,
    date: "January 18, 2019",
    category: "Storage",
    excerpt: `If you're preparing for a move, you are probably realizing that you have more belongings than you thought. Temporary storage can help you organize and keep safe`,
    image: BRAND_IMAGES.warehouseCrates,
    readTime: "3 min read",
  },
  {
    slug: "what-not-to-pack-when-moving-non-allowable-items-explained",
    title: `What Not to Pack When Moving: Non-Allowable Items Explained`,
    date: "August 7, 2018",
    category: "Packing Tips",
    excerpt: `A professional moving company will transport anything that you ask them to, right? Actually, most moving companies have certain items that they cannot transport`,
    image: BRAND_IMAGES.crewWrappingOffice,
    readTime: "3 min read",
  },
  {
    slug: "how-much-do-you-tip-movers",
    title: `How Much To Tip Movers?`,
    date: "March 18, 2021",
    category: "Moving Costs",
    excerpt: `Do You Need to Tip Movers? Here are five things to consider when deciding how much to tip movers. Read more on this article!`,
    image: BRAND_IMAGES.crewLoadingTruckRamp,
    readTime: "7 min read",
  },
  {
    slug: "simplify-move-turn-move-road-trip",
    title: `How to Simplify Your Move: Turn Your Move Into a Road Trip`,
    date: "June 5, 2017",
    category: "Moving Tips",
    excerpt: `Moving from one place to another presents unique challenges to your family, especially when the move is a far one. However, there are several things you can do `,
    image: BRAND_IMAGES.crewCarryingFurniture,
    readTime: "4 min read",
  },
  {
    slug: "organizing-small-spaces",
    title: `14 Organizing Tips For Maximizing A Small Space`,
    date: "September 27, 2019",
    category: "Moving Tips",
    excerpt: `Minimalizing and moving to smaller homes is a growing movement in the 21st Century. How do you organize and maximize the space in your house?`,
    image: BRAND_IMAGES.crewCarryingOut,
    readTime: "6 min read",
  },
  {
    slug: "how-to-choose-the-best-neighborhood-when-moving-to-a-new-city",
    title: `How to Choose the Best Neighborhood When Moving to a New City`,
    date: "April 4, 2019",
    category: "Local Guides",
    excerpt: `What should you take into consideration when making the decision to move? Read the most important factors to consider when choosing to live in a city.`,
    image: BRAND_IMAGES.truckSeattleSkyline,
    readTime: "3 min read",
  },
  {
    slug: "moving-101-how-to-pack-your-electronics-for-moving",
    title: `Moving 101: How to Pack Your Electronics for Moving`,
    date: "January 17, 2017",
    category: "Packing Tips",
    excerpt: `If you're wondering how to pack your electronics for moving, here's how to safely transport your desk to the new home.`,
    image: BRAND_IMAGES.truckSeattleSkyline,
    readTime: "4 min read",
  },
  {
    slug: "5-questions-before-hiring-commercial-moving-company",
    title: `5 Questions to Ask Before Hiring a Moving Company (Seattle Checklist)`,
    date: "September 23, 2015",
    category: "Commercial Moving",
    excerpt: `Not all moving companies are created equal. Before you sign anything, ask these 5 questions to protect your belongings and avoid hidden fees.`,
    image: BRAND_IMAGES.officeMoveAction,
    readTime: "3 min read",
  },
  {
    slug: "moving-hacks",
    title: `25 Clever Moving Hacks and Advice to Make Your Move Less Stressful`,
    date: "August 8, 2023",
    category: "Moving Tips",
    excerpt: `With the moving hacks here go for a better and faster move. Read to find some great moving tips to avoid stress and save money. Contact us today!`,
    image: BRAND_IMAGES.crewCarryingUpRamp,
    readTime: "3 min read",
  },
  {
    slug: "10-expert-tips-to-make-your-winter-move-an-easier-mission",
    title: `10 Expert Tips For Easier Moving In The Winter`,
    date: "December 20, 2018",
    category: "Moving Costs",
    excerpt: `Moving in the winter can actually be great timing, check out our tips to make your life easier. Make your plans and prepping ahead and let us help you handle th`,
    image: BRAND_IMAGES.truckBellevueSkyline,
    readTime: "4 min read",
  },
  {
    slug: "11-tips-for-an-easy-diy-move",
    title: `11 Tips For An Easy DIY Move You Should Know`,
    date: "December 1, 2021",
    category: "Moving Costs",
    excerpt: `There are a lot of ways to simplify your DIY move. Here are our top 11 tips for a smooth and easy DIY move. Check out and read now for more information.`,
    image: BRAND_IMAGES.truckResidentialBuilding,
    readTime: "4 min read",
  },
  {
    slug: "10-things-you-need-when-moving-into-your-new-home",
    title: `10 Things You Need When Moving Into Your New Home`,
    date: "March 19, 2018",
    category: "Moving Tips",
    excerpt: `Are you getting ready to move into a new house, but are not sure if you have everything you need? We've collected an important list of 10 things you may need to`,
    image: BRAND_IMAGES.threeCrewLoadingTruck,
    readTime: "4 min read",
  },
  {
    slug: "advantages-of-warehousing",
    title: `Benefits & Advantages of Warehousing`,
    date: "March 26, 2023",
    category: "Moving Tips",
    excerpt: `The advantages of warehousing benefit businesses from reduced delivery time to storing benefits. Learn how warehousing helps proprietors & consumers!`,
    image: BRAND_IMAGES.brandedTruck,
    readTime: "4 min read",
  },
  {
    slug: "15-signs-of-a-worst-moving-company",
    title: `15 Signs of a Worst Moving Company`,
    date: "May 30, 2022",
    category: "Moving Tips",
    excerpt: `Read On The Moving’s blog article about the list of signs of the worst moving companies you should remember before moving.`,
    image: BRAND_IMAGES.threeCrewRampLoading,
    readTime: "3 min read",
  },
  {
    slug: "what-to-pack-first-moving",
    title: `Tips For What To Pack First When You're Moving`,
    date: "January 11, 2020",
    category: "Packing Tips",
    excerpt: `Deciding to what to pack first can feel like a daunting task. To help your move go smoothly and stress-free, we've complied a step by step list.`,
    image: BRAND_IMAGES.truckResidentialStreet,
    readTime: "5 min read",
  },
  {
    slug: "how-to-meet-your-neighbors",
    title: `How To Meet Your New Neighbors | 7 Non-Awkward Tips For Introducing Yourself`,
    date: "September 27, 2019",
    category: "Moving Tips",
    excerpt: `A professional moving company will take care of all the packing, loading, and actual moving freeing you up to meet the neighbors!`,
    image: BRAND_IMAGES.crewHoodieAtTruck,
    readTime: "4 min read",
  },
  {
    slug: "how-many-trips-does-a-local-move-really-take",
    title: `How Many Trips Does a Local Move Really Take?`,
    date: "December 21, 2024",
    category: "Moving Tips",
    excerpt: `Planning a move? Discover how many trips for a local move it takes and learn tips to minimize moving truck trips for local moves efficiently`,
    image: BRAND_IMAGES.crewEntryway1,
    readTime: "3 min read",
  },
  {
    slug: "furniture-storage-units",
    title: `Finding The Furniture Storage Units For Long-Term and Short-Term Storage`,
    date: "March 21, 2024",
    category: "Storage",
    excerpt: `When moving, furniture storage units are an excellent way to keep your furniture accessible, safe, and secure. Contact On The Go Moving, for professional assist`,
    image: BRAND_IMAGES.crewCarryingFurniture,
    readTime: "3 min read",
  },
  {
    slug: "top-7-tips-for-a-smooth-move-a-moving-companys-recommendations-for-your-moving-day",
    title: `Top 7 Moving Day Tips: How To Enjoy Your Moving Day`,
    date: "March 16, 2015",
    category: "Moving Costs",
    excerpt: `When it comes to your moving day, you need all the help you can get. In this article we offer great moving tips from the pros on packing, moving`,
    image: BRAND_IMAGES.crewLoadingTruckRamp,
    readTime: "5 min read",
  },
  {
    slug: "mercer-island-movers",
    title: `Living in Mercer Island, WA: What to Know Before You Move`,
    date: "2024-01-01",
    category: "Moving Tips",
    excerpt: `Mercer Island is one of the most desirable places to live in the Seattle metro. Here's what residents love about island life — and what surprises newcomers.`,
    image: BRAND_IMAGES.customerHandshake,
    readTime: "3 min read",
  },
  {
    slug: "best-things-to-do-in-everett-wa",
    title: `10 Exciting Things To Do In Everett In 2021`,
    date: "January 1, 2021",
    category: "Local Guides",
    excerpt: `Discover the best things to do in Everett, WA, including waterfront attractions, parks, museums, dining, and family-friendly activities.`,
    image: BRAND_IMAGES.truckSeattleSkyline,
    readTime: "4 min read",
  },
  {
    slug: "living-in-west-seattle",
    title: `7 Important Things To Know About Living In West Seattle, WA in 2022`,
    date: "January 6, 2021",
    category: "Local Guides",
    excerpt: `Thinking about living in West Seattle, WA? Discover lifestyle, housing, parks, local culture, commute options, and what makes this neighborhood unique.`,
    image: BRAND_IMAGES.truckSeattleSkyline,
    readTime: "5 min read",
  },
  {
    slug: "reasons-in-moving-to-bellevue-wa",
    title: `Reasons in Moving to Bellevue, WA`,
    date: "July 15, 2022",
    category: "Local Guides",
    excerpt: `Need to know what are the top reasons to move to Bellevue WA? Read this article from On The Go Moving and learn more.`,
    image: BRAND_IMAGES.truckBellevueSkyline,
    readTime: "3 min read",
  },
  {
    slug: "how-to-announce-your-office-relocation-5-great-tips",
    title: `How to Announce Your Office Relocation 5 Great Tips`,
    date: "November 29, 2021",
    category: "Commercial Moving",
    excerpt: `Here are the great top five tips on how you can announce your office relocation to your employees. Be positive and upbeat. Check out now for more info.`,
    image: BRAND_IMAGES.officeMoveAction,
    readTime: "3 min read",
  },
  {
    slug: "best-time-to-rent-an-apartment-guide",
    title: `Best Time to Rent an Apartment An Essential Guide`,
    date: "September 1, 2022",
    category: "Specialty Moving",
    excerpt: `Need to know which is the best time to rent an apartment? Read this article from On The Go Moving and learn more.`,
    image: BRAND_IMAGES.crewLoadingTruckRamp,
    readTime: "3 min read",
  },
  {
    slug: "how-to-fold-for-packing",
    title: `How to Fold Clothes for Packing: Best Way to Fold for Suitcases`,
    date: "March 26, 2023",
    category: "Packing Tips",
    excerpt: `Figuring how to fold clothes for packing is important to avoid wrinkles. Find out how to fold, roll & arrange clothes to save space when you travel!`,
    image: BRAND_IMAGES.truckSeattleSkyline,
    readTime: "3 min read",
  },
  {
    slug: "essential-tools-needed-for-a-smooth-move",
    title: `Essential Tools Needed for a Smooth Move`,
    date: "August 22, 2024",
    category: "Moving Tips",
    excerpt: `Discover essential packing supplies and tools like the heavy duty dolly needed for a smooth move. Ensure your belongings are secure and easy to transport.`,
    image: BRAND_IMAGES.crewStaircaseExit,
    readTime: "3 min read",
  },
  {
    slug: "eco-friendly-moving-sustainable-practices-for-your-next-move",
    title: `Eco-Friendly Moving: Sustainable Practices for Your Next Move`,
    date: "December 21, 2024",
    category: "Moving Tips",
    excerpt: `Make your move sustainable with eco-friendly moving tips. Use environmentally friendly moving boxes and hire green movers for a low-waste relocation.`,
    image: BRAND_IMAGES.threeCrewRampLoading,
    readTime: "3 min read",
  },
  {
    slug: "moving-elderly-parents-out-of-their-home",
    title: `How To Relocate Your Elderly Parents Smoothly For Them`,
    date: "May 15, 2019",
    category: "Senior Moving",
    excerpt: `It can be hard when it comes time to move your elderly parents. To help the process go smoothly, we've compiled 7 tips for you and them.`,
    image: BRAND_IMAGES.residentialService,
    readTime: "3 min read",
  },
  {
    slug: "10-things-to-know-about-living-in-ballard",
    title: `10 Things to Know About Living in Ballard`,
    date: "December 26, 2017",
    category: "Local Guides",
    excerpt: `Life in Ballard has a ton to offer in terms of reasonable housing prices, a growing scene for food and nightlife, reputable school systems, safety, and a stable`,
    image: BRAND_IMAGES.truckSeattleSkyline,
    readTime: "4 min read",
  },
  {
    slug: "how-to-pack-shoes-for-moving-8-tips",
    title: `8 Tips On How To Pack Shoes For Moving`,
    date: "September 28, 2019",
    category: "Packing Tips",
    excerpt: `Remove the stress of packing your shoe collection, here are 8 simple tips to sort through and pack your shoe for moving. Don't forget to leave a pair out for mo`,
    image: BRAND_IMAGES.truckProfessionalLot,
    readTime: "4 min read",
  },
  {
    slug: "renting-a-house-for-the-first-time",
    title: `5 Tips For Renting A House For The First Time`,
    date: "July 23, 2019",
    category: "Moving Tips",
    excerpt: `Before you sign the lease on your first rental, there are a couple of things you should know. Read more information in our blog post.`,
    image: BRAND_IMAGES.crewHoodieAtTruck,
    readTime: "5 min read",
  },
  {
    slug: "living-on-mercer-island",
    title: `Living On Mercer Island Washington`,
    date: "January 22, 2021",
    category: "Local Guides",
    excerpt: `Want to know what living on Mercer Island is like? Lucky for you, residents that live in Mercer Island Washington have great things to say about their community`,
    image: BRAND_IMAGES.truckBellevueSkyline,
    readTime: "3 min read",
  },
  {
    slug: "living-in-west-bellevue-washington",
    title: `Living In West Bellevue Washington`,
    date: "April 16, 2021",
    category: "Local Guides",
    excerpt: `Learn more about the West Bellevue, Washington cost of living, the population of the city, as well as the best things to do in West Bellevue WA. Visit On the go`,
    image: BRAND_IMAGES.truckBellevueSkyline,
    readTime: "4 min read",
  },
  {
    slug: "living-in-everett-wa-you-need-to-know",
    title: `Living in Everett WA: Everything You Need to Know`,
    date: "September 1, 2022",
    category: "Local Guides",
    excerpt: `Are there any advantages to living in Everett, WA? Read this article on On The Go Moving & Storage to find out all the things to know about living here.`,
    image: BRAND_IMAGES.truckBrickBuilding,
    readTime: "3 min read",
  },
  {
    slug: "living-in-bothell-wa",
    title: `Living in Bothell WA`,
    date: "April 13, 2021",
    category: "Local Guides",
    excerpt: `Learn more about the Bothell Washington cost of living, the population of the city, as well as the best things to do in Bothell WA. Visit On the go moving to fi`,
    image: BRAND_IMAGES.truckResidentialStreet,
    readTime: "3 min read",
  },
  {
    slug: "green-moving-eco-friendly-10-tips",
    title: `Green Moving: 10 Tips How To Make Your Next Move Eco-Friendly for Earth Day 2021`,
    date: "January 7, 2021",
    category: "Moving Costs",
    excerpt: `Learn 10 actionable eco-friendly moving tips to reduce waste and carbon footprint during your next relocation.`,
    image: BRAND_IMAGES.truckKirklandHouse,
    readTime: "4 min read",
  },
  {
    slug: "living-in-woodinville-wa",
    title: `10 Things to Know About Living in Woodinville`,
    date: "March 3, 2021",
    category: "Local Guides",
    excerpt: `Woodinville is a delightful community that lies to the Northeast of Seattle. Let’s take a look at 10 things to know about living in Woodinville.`,
    image: BRAND_IMAGES.truckKirklandHouse,
    readTime: "4 min read",
  },
  {
    slug: "things-to-do-in-lynnwood-wa",
    title: `Things to Do in Lynnwood WA`,
    date: "September 2, 2021",
    category: "Local Guides",
    excerpt: `No matter whether you're planning a visit or to stay, you can count on a variety of fun things to do in Lynnwood, Washington. Read more!`,
    image: BRAND_IMAGES.truckBrickBuilding,
    readTime: "4 min read",
  },
  {
    slug: "living-in-renton-wa",
    title: `15 Things to Know About Living in Renton`,
    date: "August 4, 2020",
    category: "Local Guides",
    excerpt: `Thinking about living in Renton, Washington? Here are 15 things you will need to know before you make the big move to the southeast shore of Lake Washington`,
    image: BRAND_IMAGES.truckResidentialBuilding,
    readTime: "3 min read",
  },
  {
    slug: "things-to-do-in-edmonds-wa",
    title: `Things to Do in Edmonds WA`,
    date: "September 2, 2021",
    category: "Local Guides",
    excerpt: `From outdoor activities to community-wide events, you can find many fun things to do in Edmonds, WA. They have the best restaurants too! Read more!`,
    image: BRAND_IMAGES.truckBrickBuilding,
    readTime: "4 min read",
  },
  {
    slug: "things-to-do-on-mercer-island",
    title: `Things to do on Mercer Island`,
    date: "June 2, 2021",
    category: "Local Guides",
    excerpt: `Don’t forget to share all of your local tips in the comments below and tell us what your favorite thing to do on Mercer Island is!Need help planning a move to M`,
    image: BRAND_IMAGES.truckBellevueSkyline,
    readTime: "3 min read",
  },
  {
    slug: "things-to-do-in-sammamish",
    title: `Things To Do In Sammamish`,
    date: "February 7, 2021",
    category: "Local Guides",
    excerpt: `Sammamish is full of all kind of events and activities to explore. Learn more about the area and the things to do in Sammamish!`,
    image: BRAND_IMAGES.truckResidentialBuilding,
    readTime: "3 min read",
  },
  {
    slug: "things-to-do-in-kirkland-wa",
    title: `Things to Do in Kirkland, WA`,
    date: "October 1, 2020",
    category: "Local Guides",
    excerpt: `Looking for things to do in Kirkland, WA? Explore waterfront parks, dining, shopping, outdoor activities, and local attractions for all ages.`,
    image: BRAND_IMAGES.truckKirklandHouse,
    readTime: "4 min read",
  },
  {
    slug: "things-to-do-in-woodinville",
    title: `Things to Do in Woodinville`,
    date: "March 3, 2021",
    category: "Local Guides",
    excerpt: `If you are planning to move or visit to Woodinville WA soon, then find out the things to do in while there? When moving across the country to Woodinville or fro`,
    image: BRAND_IMAGES.truckKirklandHouse,
    readTime: "5 min read",
  },
  {
    slug: "fun-things-to-do-in-bothell-wa",
    title: `10 Fun Things To Do In Bothell WA in 2021 | Plus Free Things To Do With Kids`,
    date: "January 6, 2021",
    category: "Local Guides",
    excerpt: `Explore the best things to do in Bothell, WA — from outdoor parks and family activities to local dining and entertainment. Discover top attractions and insider `,
    image: BRAND_IMAGES.truckResidentialStreet,
    readTime: "4 min read",
  },
  {
    slug: "things-to-do-in-bellevue",
    title: `15 Best Things To Do In Bellevue For Fun`,
    date: "July 20, 2020",
    category: "Local Guides",
    excerpt: `Bellevue is known for its beautiful sites and downtown skyline of gleaming high-rises. Find things to do in Bellevue WA at night or fun activities with kids. Do`,
    image: BRAND_IMAGES.truckBellevueSkyline,
    readTime: "4 min read",
  },
  {
    slug: "how-to-prepare-for-movers",
    title: `How to Prepare for Movers to Arrive?`,
    date: "August 23, 2023",
    category: "Moving Tips",
    excerpt: `After hiring a moving company for your upcoming move, you must know how to prepare for movers. To prepare for your movers before they arrive on a moving day.`,
    image: BRAND_IMAGES.truckProfessionalLot,
    readTime: "3 min read",
  },
  {
    slug: "how-to-protect-fragile-items-during-a-move",
    title: `How to Protect Fragile Items During a Move`,
    date: "December 20, 2024",
    category: "Moving Tips",
    excerpt: `Learn how to pack fragile items for moving safely. Get expert advice on protecting glass during a move and preventing damage with smart packing techniques.`,
    image: BRAND_IMAGES.crewEntryway2,
    readTime: "3 min read",
  },
  {
    slug: "things-to-do-in-issaquah",
    title: `15 Top Things To Do In Issaquah`,
    date: "June 8, 2020",
    category: "Local Guides",
    excerpt: `The Pacific Northwest is a beautiful and interesting place to live, and Issaquah is no exception. Here are 15 places to check out after your Issaquah move.`,
    image: BRAND_IMAGES.truckResidentialStreet,
    readTime: "5 min read",
  },
  {
    slug: "living-in-kirkland-wa",
    title: `10 Things To Know About Living In Kirkland, WA`,
    date: "January 13, 2020",
    category: "Local Guides",
    excerpt: `Considering a move to Kirkland, WA? Here are 10 important things you should know about living in Kirkland before taking the big step.`,
    image: BRAND_IMAGES.truckKirklandHouse,
    readTime: "5 min read",
  },
  {
    slug: "how-to-move-large-furniture-safely-and-efficiently",
    title: `How to Move Large Furniture Safely and Efficiently`,
    date: "December 20, 2024",
    category: "Specialty Moving",
    excerpt: `Learn furniture moving techniques to handle bulky items safely. Discover safe ways to move heavy furniture and tips for moving it upstairs efficiently`,
    image: BRAND_IMAGES.crewEntryway3,
    readTime: "3 min read",
  },
  {
    slug: "best-restaurants-in-seattle",
    title: `Best Seattle Seafood & International Restaurants to Visit in 2022`,
    date: "November 18, 2015",
    category: "Local Guides",
    excerpt: `On The Go Moving shares the names of several wonderful Seattle restaurants so that newcomers can enjoy the beauty and diversity of the city.`,
    image: BRAND_IMAGES.truckSeattleSkyline,
    readTime: "4 min read",
  },
  {
    slug: "attractions-in-seattle",
    title: `Seattle Attractions - Places To Visit in the Emerald City`,
    date: "July 4, 2023",
    category: "Local Guides",
    excerpt: `Find Seattle attractions to know the best places and the best things to do in Seattle. Know more about the top-rated & must-see attractions. Visit us today!`,
    image: BRAND_IMAGES.truckSeattleSkyline,
    readTime: "4 min read",
  },
  {
    slug: "shopping-in-seattle",
    title: `Seattle Shopping: The Best Places for New Residents to Visit`,
    date: "March 26, 2023",
    category: "Local Guides",
    excerpt: `Find the best options while shopping in Seattle. We can show you the best options in the downtown shopping district!`,
    image: BRAND_IMAGES.truckSeattleSkyline,
    readTime: "4 min read",
  },
  {
    slug: "things-to-do-in-seattle-in-summer",
    title: `15 Fun Things To Do In Seattle In Summer`,
    date: "July 7, 2020",
    category: "Local Guides",
    excerpt: `Summers in Seattle, the seaport city of the West Coast, are unmatched. Here are 15 fun things to do in the city this summer to truly experience Seattle.`,
    image: BRAND_IMAGES.truckSeattleSkyline,
    readTime: "3 min read",
  },
  {
    slug: "best-places-to-live-in-seattle-neighborhoods-near-the-area",
    title: `Best Places To Live In Seattle: Neighborhoods Near The Area`,
    date: "May 16, 2023",
    category: "Local Guides",
    excerpt: `Learn about the best places to live in Seattle, we will guide you through the best neighborhoods in the area. Don’t miss our gems for buyers!`,
    image: BRAND_IMAGES.truckSeattleSkyline,
    readTime: "3 min read",
  },
  {
    slug: "living-in-fremont-seattle",
    title: `Living in Fremont Seattle`,
    date: "August 31, 2020",
    category: "Local Guides",
    excerpt: `Fremont is situated along the Fremont Cut of the Lake Washington Ship Canal to the north of Queen Anne, Seattle. Fremont has something for everyone, no matter i`,
    image: BRAND_IMAGES.truckSeattleSkyline,
    readTime: "5 min read",
  },
  {
    slug: "bellevue-or-seattle-where-to-live",
    title: `Bellevue or Seattle Where To Live`,
    date: "July 5, 2021",
    category: "Local Guides",
    excerpt: `Learn more about the pros and cons of Bellevue vs Seattle for living, or get in touch with On The Go Moving to speak with a reliable moving service about your r`,
    image: BRAND_IMAGES.truckBellevueSkyline,
    readTime: "3 min read",
  },
  {
    slug: "living-in-beacon-hill-seattle",
    title: `Living in Beacon Hill, Seattle: A Neighborhood Overview`,
    date: "September 14, 2020",
    category: "Local Guides",
    excerpt: `Considering living in Beacon Hill, Seattle? Learn about housing, lifestyle, parks, transit, and what makes this neighborhood a great place to live.`,
    image: BRAND_IMAGES.truckSeattleSkyline,
    readTime: "5 min read",
  },
  {
    slug: "seattle-packing-tips-plastic-bins-or-cardboard-boxes",
    title: `Seattle Packing Tips: Plastic Bins or Cardboard Boxes?`,
    date: "September 2, 2016",
    category: "Packing Tips",
    excerpt: `Are you packing for a move? Here are the pros and cons between cardboard boxes and plastic bins. Read on for helpful Seattle packing tips:`,
    image: BRAND_IMAGES.truckBrickBuilding,
    readTime: "3 min read",
  },
  {
    slug: "living-in-capitol-hill-seattle",
    title: `12 Interesting Things You Should Know About Living In Capitol Hill, Seattle`,
    date: "September 27, 2019",
    category: "Local Guides",
    excerpt: `Are you considering a move to the Capitol Hill neighborhood of Seattle, Washington? If so, then here are 12 things you should know about your new home town.`,
    image: BRAND_IMAGES.truckSeattleSkyline,
    readTime: "4 min read",
  },
  {
    slug: "moving-to-seattle-after-graduation",
    title: `What Is Living in Seattle As Young Adult Like?`,
    date: "July 8, 2016",
    category: "Local Guides",
    excerpt: `Seattle has a triving young adult culture and that's a main reason so many millennials are deciding to live and work in Seattle. Is it right for you?`,
    image: BRAND_IMAGES.truckSeattleSkyline,
    readTime: "3 min read",
  },
  {
    slug: "living-in-belltown-seattle-wa",
    title: `Living in Belltown, Seattle, WA: A Neighborhood Overview`,
    date: "October 16, 2020",
    category: "Local Guides",
    excerpt: `Thinking about living in Belltown, Seattle, WA? Learn about housing, lifestyle, walkability, nightlife, and what daily life is like in Belltown.`,
    image: BRAND_IMAGES.truckSeattleSkyline,
    readTime: "4 min read",
  },
  {
    slug: "living-in-queen-anne-seattle",
    title: `Living in Queen Anne Seattle`,
    date: "October 23, 2020",
    category: "Local Guides",
    excerpt: `Thinking about living in Queen Anne, Seattle? Learn about housing, views, walkability, parks, and what daily life is like in this iconic neighborhood.`,
    image: BRAND_IMAGES.truckSeattleSkyline,
    readTime: "4 min read",
  },
  {
    slug: "parks-near-downtown-seattle",
    title: `Parks Near Downtown Seattle, WA`,
    date: "June 3, 2022",
    category: "Local Guides",
    excerpt: `Welcome to the official On The Go Moving site. Go through the blog post to see the best Parks Near Downtown Seattle, WA that makes Seattle such an exciting urba`,
    image: BRAND_IMAGES.truckSeattleSkyline,
    readTime: "3 min read",
  },
  {
    slug: "moving-to-seattle",
    title: `30 Things to Know Before Moving to Seattle | Eastside Relocation Guide`,
    date: "March 15, 2021",
    category: "Local Guides",
    excerpt: `Planning a move to Seattle? Discover neighborhoods, cost of living, weather, and insider tips from locals who know the Emerald City best.`,
    image: BRAND_IMAGES.truckSeattleSkyline,
    readTime: "5 min read",
  },
  {
    slug: "restaurant-in-redmond",
    title: `Best Restaurants in Redmond WA`,
    date: "January 7, 2022",
    category: "Local Guides",
    excerpt: `Looking for the best restaurant around Redmond that offers healthy and delicious foods? This article is what you're looking for! Read more and call us today!`,
    image: BRAND_IMAGES.truckResidentialStreet,
    readTime: "3 min read",
  },
  {
    slug: "best-things-to-do-in-redmond",
    title: `22 Top Things To Do in Redmond`,
    date: "June 4, 2021",
    category: "Local Guides",
    excerpt: `Explore the best things to do in Redmond, WA — parks, trails, tech attractions, family fun, shopping, and local experiences for residents and visitors.`,
    image: BRAND_IMAGES.truckResidentialStreet,
    readTime: "4 min read",
  },
  {
    slug: "10-things-you-should-know-about-living-in-redmond-washington",
    title: `10 Things You Should Know About Living in Redmond, Washington`,
    date: "March 17, 2016",
    category: "Local Guides",
    excerpt: `If you're thinking about moving to Redmond, On The Go Moving has a list of 10 things you should know. `,
    image: BRAND_IMAGES.truckResidentialStreet,
    readTime: "5 min read",
  },
  {
    slug: "things-to-do-in-shoreline-wa",
    title: `Things to Do in Shoreline, WA: Parks, Attractions & Activities`,
    date: "November 21, 2020",
    category: "Local Guides",
    excerpt: `Discover the best things to do in Shoreline, WA, including parks, outdoor activities, dining, and local attractions for all ages.`,
    image: BRAND_IMAGES.truckResidentialStreet,
    readTime: "4 min read",
  },
  {
    slug: "parks-in-bellevue",
    title: `Parks In Bellevue WA | Water Recreation, Park Near Bellevue Square`,
    date: "July 11, 2020",
    category: "Local Guides",
    excerpt: `Bellevue is known for having some beautiful parks. Form lushish green to refreshing water, check out the top 7 parks to visit in the Bellevue area!`,
    image: BRAND_IMAGES.truckBellevueSkyline,
    readTime: "4 min read",
  },
  {
    slug: "living-in-downtown-seattle",
    title: `What Is It Like Living in Downtown Seattle? | Cost of Living, Parking, Traffic,`,
    date: "May 12, 2020",
    category: "Local Guides",
    excerpt: `Downtown Seattle can be an exciting place to live! Before you take the leap to live in the center of the Emerald City, here are four things you should know.`,
    image: BRAND_IMAGES.truckSeattleSkyline,
    readTime: "4 min read",
  },
  {
    slug: "parks-in-lynnwood",
    title: `Best Parks in Lynnwood`,
    date: "November 23, 2021",
    category: "Local Guides",
    excerpt: `Discover the best trails, hiking and other outdoor activities in the best parks in lynnwood. On the Go moving has different locations to explore.`,
    image: BRAND_IMAGES.truckBrickBuilding,
    readTime: "3 min read",
  },
  {
    slug: "seattle-restaurant-fremont",
    title: `Best Restaurants in Fremont Seattle, WA`,
    date: "January 11, 2022",
    category: "Local Guides",
    excerpt: `Are you looking for the best restaurants in Fremont, Seattle that will satisfy your cravings? This article is for you. Read more to find out!`,
    image: BRAND_IMAGES.truckSeattleSkyline,
    readTime: "3 min read",
  },
  {
    slug: "lake-sammamish-parks",
    title: `Lake Sammamish Parks`,
    date: "August 3, 2021",
    category: "Local Guides",
    excerpt: `Are you looking for the ideal park in Lake Sammamish? Visit On The Go Moving, to learn about the best parks & things to do in and around Sammamish, Washington.`,
    image: BRAND_IMAGES.truckResidentialBuilding,
    readTime: "3 min read",
  },
  {
    slug: "kirkland-waterfront",
    title: `Kirkland Waterfront`,
    date: "August 9, 2021",
    category: "Local Guides",
    excerpt: `Learn more about the Kirkland's iconic waterfront, find the best parks, trails, and waterfront restaurants in the area. Visit On The Go Moving for more details.`,
    image: BRAND_IMAGES.truckKirklandHouse,
    readTime: "3 min read",
  },
  {
    slug: "parks-in-redmond-wa",
    title: `Redmond Parks`,
    date: "June 7, 2021",
    category: "Local Guides",
    excerpt: `Discover the best parks in Redmond WA, from trails to family-friendly spaces, plus local tips for living and moving in Redmond.`,
    image: BRAND_IMAGES.truckResidentialStreet,
    readTime: "5 min read",
  },
  {
    slug: "what-is-seattle-known-for-food-sights",
    title: `What Seattle Is Known For — Best Food & Iconic Sights`,
    date: "April 29, 2021",
    category: "Local Guides",
    excerpt: `Explore what Seattle is known for — iconic food and best sights from Pike Place Market to Space Needle, plus local travel tips and moving insights.`,
    image: BRAND_IMAGES.truckSeattleSkyline,
    readTime: "4 min read",
  },
  {
    slug: "mercer-island-restaurants",
    title: `The Best Restaurants, Parks, & Recreation Centers in Mercer Island`,
    date: "November 23, 2021",
    category: "Local Guides",
    excerpt: `Looking for best restaurants, parks and recreation center in Mercer Island?On the Go moving has different locations to explore. Learn more.`,
    image: BRAND_IMAGES.truckBellevueSkyline,
    readTime: "3 min read",
  },
  {
    slug: "how-to-move-a-piano",
    title: `Do It Yourself: Best Way To Move A Piano`,
    date: "November 20, 2019",
    category: "Specialty Moving",
    excerpt: `Moving your piano can be daunting task. Here are our expert tips to make sure your piano and your back both remain intact throughout the process.`,
    image: BRAND_IMAGES.crewRamp,
    readTime: "4 min read",
  },
  {
    slug: "when-is-the-best-time-to-move-into-an-apartment",
    title: `When Is the Best Time to Move Into an Apartment?`,
    date: "November 2, 2022",
    category: "Specialty Moving",
    excerpt: `Need to know which is the best time to move into an apartment? Read this article from On The Go Moving and learn more.`,
    image: BRAND_IMAGES.crewDoorway2,
    readTime: "4 min read",
  },
  {
    slug: "office-moving-tips",
    title: `How To Keep Your Office Moving Organized And Easy`,
    date: "August 1, 2017",
    category: "Commercial Moving",
    excerpt: `Moving an entire office can at first seem overwhelming. To combat potential chaos, we've created a month by month office moving plan to keep you organized.`,
    image: BRAND_IMAGES.crewWrappingOffice,
    readTime: "4 min read",
  },
  {
    slug: "best-office-organization-systems",
    title: `Office Organization Systems | How To Organize An Office Space | Tips For Arranging Your Work`,
    date: "March 23, 2020",
    category: "Commercial Moving",
    excerpt: `Struggling to keep your office organized? Follow our eight easy steps to arrange your space into a system that works for you and your team.`,
    image: BRAND_IMAGES.officeMoveAction,
    readTime: "4 min read",
  },
  {
    slug: "things-to-do-in-downtown-seattle-washington",
    title: `Things to Do in Downtown Seattle WA`,
    date: "February 22, 2022",
    category: "Local Guides",
    excerpt: `Wondering what to do in Seattle, WA? Check out these exciting and fun things to do in Downtown Seattle, WA for an epic travel adventure.`,
    image: BRAND_IMAGES.truckSeattleSkyline,
    readTime: "4 min read",
  },
  {
    slug: "residential-moving-services-guide",
    title: `What's Included in a Residential Move? A Plain-English Guide for Seattle Homeowners`,
    date: "November 28, 2023",
    category: "Moving Tips",
    excerpt: `Confused about what residential movers actually do? This guide breaks down every service — loading, packing, storage, and more — so you know exactly what to expect.`,
    image: BRAND_IMAGES.crewEntryway1,
    readTime: "4 min read",
  },
  {
    slug: "how-to-pack-clothes-for-moving",
    title: `How to Pack Clothes For Moving | Best Way To Move Clothes`,
    date: "November 29, 2019",
    category: "Packing Tips",
    excerpt: `Packing clothes for moving can seem like a daunting task, make it easy for yourself by exploring our best tips for how to pack your clothes efficiently and simp`,
    image: BRAND_IMAGES.truckResidentialStreet,
    readTime: "6 min read",
  },
  {
    slug: "living-in-bellevue-wa",
    title: `20 Things You Should Know Before Moving To Bellevue, WA`,
    date: "May 30, 2021",
    category: "Local Guides",
    excerpt: `When most people think of Bellevue, they tend to think of it as a suburb of Seattle. If you’ve been considering moving to Bellevue, you’re probably eager to lea`,
    image: BRAND_IMAGES.truckBellevueSkyline,
    readTime: "5 min read",
  },
  {
    slug: "moving-to-a-new-city-alone",
    title: `Moving To A New City Alone | What To Do & How To Face The Challenges Of Moving Out Of State`,
    date: "January 13, 2020",
    category: "Moving Tips",
    excerpt: `Moving to a new city alone can feel frightening and lonely. Sometimes you feel you just don't know what to do next or how to fit in. To help make this next exci`,
    image: BRAND_IMAGES.crewCarryingFurniture,
    readTime: "3 min read",
  },
  {
    slug: "things-to-do-in-seattle-in-winter",
    title: `Things To Do in Seattle in Winter`,
    date: "January 5, 2021",
    category: "Local Guides",
    excerpt: `If you're looking for things to do in Seattle during winter, then time to discover all Seattle has to offer. Seattle has no shortage of fun things to do during `,
    image: BRAND_IMAGES.truckSeattleSkyline,
    readTime: "5 min read",
  },
  {
    slug: "apartment-moving-tips",
    title: `Apartment Moving Tips: What Renters Need to Know Before Move Day`,
    date: "May 21, 2020",
    category: "Specialty Moving",
    excerpt: `Elevator reservations, parking permits, narrow hallways — apartment moves have unique challenges. Here's how to prepare so nothing slows you down.`,
    image: BRAND_IMAGES.crewLoadingTruckRamp,
    readTime: "5 min read",
  }
];

export const BLOG_CATEGORIES = ["All", "Commercial Moving", "Local Guides", "Moving Costs", "Moving Tips", "Packing Tips", "Senior Moving", "Specialty Moving", "Storage"];
